import type {G2Spec} from "@antv/g2";
import {chartPadding, compactChartPadding, studioTheme} from "../theme";
import type {
  FactoryContext,
  G2StudioDesign,
  ProviderDataContract,
  ProviderDesignCapability,
  ProviderStructure,
  StudioRow,
  StudioRowField,
} from "../types";
import {content, industryRows, row} from "../sample-content";

const base = ({content: c, controls, width, height}: FactoryContext) => ({
  width,
  height,
  autoFit: false,
  data: c.rows,
  animate: false,
  theme: "classicDark",
  padding: controls.compact ? compactChartPadding : chartPadding,
  scale: {color: {range: studioTheme.palette}},
  axis: {
    x: {labelFill: studioTheme.muted, title: false, gridStroke: studioTheme.grid},
    y: {labelFill: studioTheme.muted, title: false, grid: false},
  },
  legend: controls.showLegend ? {color: {labelFill: studioTheme.muted}} : false,
  viewStyle: {viewFill: "transparent", plotFill: "transparent"},
});

const labels = (ctx: FactoryContext, position = "right") =>
  ctx.controls.showLabels
    ? [{text: "value", position, fill: studioTheme.text, fontSize: 12}]
    : undefined;

const bar = (
  extra: Partial<G2Spec> | ((ctx: FactoryContext) => Partial<G2Spec>),
) => (ctx: FactoryContext): G2Spec => {
  const patch = typeof extra === "function" ? extra(ctx) : extra;
  return {
    ...base(ctx),
    type: "interval",
    encode: {x: "label", y: "value", color: "group"},
    style: {radiusTopLeft: 5, radiusTopRight: 5, fillOpacity: 0.94},
    labels: labels(ctx, "top"),
    ...patch,
  } as G2Spec;
};

const sorted = (rows: StudioRow[]) => [...rows].sort((a, b) => b.value - a.value);
const stackedRows = (items: string[], groups: string[]) =>
  items.flatMap((item, index) =>
    groups.map((group, g) =>
      row(`${item}-${group}`, item, 16 + index * 8 + g * 7, group),
    ),
  );

const g2Capability = ({
  dataContract = "g2-cartesian-series",
  structures = ["rows", "cartesian-series"],
  layouts,
  optionalFields = ["group", "secondaryValue", "target"],
  minRows = 1,
}: {
  dataContract?: ProviderDataContract;
  structures?: ProviderStructure[];
  layouts: string[];
  optionalFields?: StudioRowField[];
  minRows?: number;
}): ProviderDesignCapability => ({
  dataContract,
  requiredFields: {rows: ["id", "label", "value"]},
  optionalFields: {rows: optionalFields},
  structures,
  layouts,
  animationModes: [
    "grow-up",
    "grow-right",
    "radial-reveal",
    "fade-scale",
    "path-style-reveal",
  ],
  aspectRatios: ["portrait", "square", "vertical"],
  contentLimits: {minRows, maxRows: 24},
  adapter: "generic-content",
});

const g2CapabilitiesById: Record<string, ProviderDesignCapability> = {
  "g2-revenue-ranking": g2Capability({layouts: ["interval", "transpose"]}),
  "g2-rounded-ranking": g2Capability({layouts: ["interval", "transpose"]}),
  "g2-service-comparison": g2Capability({
    layouts: ["interval", "transpose", "dodgeX"],
  }),
  "g2-case-shift": g2Capability({
    layouts: ["interval", "transpose", "diverging"],
  }),
  "g2-treatment-breakdown": g2Capability({
    layouts: ["interval", "transpose", "stackY"],
  }),
  "g2-lead-source-share": g2Capability({
    layouts: ["interval", "transpose", "stackY", "normalizeY"],
  }),
  "g2-monthly-performance": g2Capability({layouts: ["interval"]}),
  "g2-channel-comparison": g2Capability({layouts: ["interval", "dodgeX"]}),
  "g2-pipeline-breakdown": g2Capability({layouts: ["interval", "stackY"]}),
  "g2-result-waterfall": g2Capability({layouts: ["interval", "waterfall-style"]}),
  "g2-goal-tracker": g2Capability({layouts: ["interval", "transpose", "bullet-style"]}),
  "g2-basic-growth": g2Capability({layouts: ["line"]}),
  "g2-multi-line": g2Capability({layouts: ["line", "series-color"]}),
  "g2-smooth-trend": g2Capability({layouts: ["line", "smooth"]}),
  "g2-area-growth": g2Capability({layouts: ["area"]}),
  "g2-stacked-area": g2Capability({layouts: ["area", "stackY"]}),
  "g2-donut-breakdown": g2Capability({
    dataContract: "g2-polar-series",
    structures: ["rows", "polar-series"],
    layouts: ["interval", "theta", "donut"],
  }),
  "g2-labeled-pie": g2Capability({
    dataContract: "g2-polar-series",
    structures: ["rows", "polar-series"],
    layouts: ["interval", "theta", "pie"],
  }),
  "g2-rose-comparison": g2Capability({
    dataContract: "g2-polar-series",
    structures: ["rows", "polar-series"],
    layouts: ["interval", "polar", "rose"],
  }),
  "g2-radial-progress": g2Capability({
    dataContract: "g2-polar-series",
    structures: ["rows", "polar-series"],
    layouts: ["interval", "theta", "radial-progress"],
  }),
  "g2-gauge-achievement": g2Capability({
    dataContract: "g2-polar-series",
    structures: ["rows", "polar-series"],
    layouts: ["interval", "theta", "gauge"],
  }),
  "g2-conversion-funnel": g2Capability({
    layouts: ["interval", "transpose", "funnel-style"],
  }),
  "g2-pyramid-stages": g2Capability({
    layouts: ["interval", "transpose", "pyramid-style"],
  }),
  "g2-radar-comparison": g2Capability({
    dataContract: "g2-polar-series",
    structures: ["rows", "polar-series"],
    layouts: ["line", "polar", "radar"],
  }),
  "g2-scatter-relationship": g2Capability({
    dataContract: "g2-point-series",
    structures: ["rows", "point-series"],
    layouts: ["point", "scatter"],
  }),
  "g2-kpi-sparkline": g2Capability({layouts: ["line", "sparkline"]}),
};

const withG2Capabilities = (
  designs: Array<Omit<G2StudioDesign, "capabilities">>,
): G2StudioDesign[] =>
  designs.map((design) => ({
    ...design,
    capabilities: g2CapabilitiesById[design.id] ?? g2Capability({layouts: ["unknown"]}),
  }));

export const g2Designs: G2StudioDesign[] = withG2Capabilities([
  {
    engine: "g2",
    id: "g2-revenue-ranking",
    name: "Revenue Ranking",
    category: "Ranking",
    description: "A portrait ranking for top-performing offers or locations.",
    industryExample: "Realtor",
    animation: "grow-right",
    supportsAddRemove: true,
    supportsSubtitle: true,
    defaultContent: content("Revenue Ranking", "Listings generating the strongest pipeline", sorted(industryRows.realtor)),
    createOptions: (ctx) => ({...bar({coordinate: {transform: [{type: "transpose"}]}, labels: labels(ctx)})(ctx)}),
  },
  {
    engine: "g2",
    id: "g2-rounded-ranking",
    name: "Market Momentum Ranking",
    category: "Ranking",
    description: "Rounded horizontal bars for short-form performance lists.",
    industryExample: "Realtor",
    animation: "grow-right",
    supportsAddRemove: true,
    supportsSubtitle: true,
    defaultContent: content("Market Momentum", "Which local actions are moving fastest", sorted(industryRows.realtor.map((r) => ({...r, value: r.value + 8})))),
    createOptions: (ctx) => bar({coordinate: {transform: [{type: "transpose"}]}, style: {radius: 10, fillOpacity: 0.96}, labels: labels(ctx)})(ctx),
  },
  {
    engine: "g2",
    id: "g2-service-comparison",
    name: "Service Comparison",
    category: "Comparison",
    description: "Grouped horizontal comparison for two service lines.",
    industryExample: "Dentist",
    animation: "grow-right",
    defaultContent: content("Service Comparison", "New demand by treatment type", [
      row("d1a", "Cleaning", 36, "This month"),
      row("d1b", "Cleaning", 28, "Last month"),
      row("d2a", "Whitening", 29, "This month"),
      row("d2b", "Whitening", 21, "Last month"),
      row("d3a", "Implants", 18, "This month"),
      row("d3b", "Implants", 13, "Last month"),
    ]),
    createOptions: (ctx) => bar({coordinate: {transform: [{type: "transpose"}]}, transform: [{type: "dodgeX"}], labels: labels(ctx)})(ctx),
  },
  {
    engine: "g2",
    id: "g2-case-shift",
    name: "Case Shift",
    category: "Comparison",
    description: "Diverging comparison for gains and losses.",
    industryExample: "Attorney",
    animation: "grow-right",
    defaultContent: content("Case Shift", "Change in qualified matters by practice area", [
      row("a1", "Family", 18, "Growth"),
      row("a2", "Estate", 11, "Growth"),
      row("a3", "Injury", -7, "Decline"),
      row("a4", "Business", 14, "Growth"),
      row("a5", "Traffic", -5, "Decline"),
    ]),
    createOptions: (ctx) => bar({coordinate: {transform: [{type: "transpose"}]}, encode: {x: "label", y: "value", color: "group"}, labels: labels(ctx)})(ctx),
  },
  {
    engine: "g2",
    id: "g2-treatment-breakdown",
    name: "Treatment Breakdown",
    category: "Breakdown",
    description: "Stacked horizontal composition for a compact offer mix.",
    industryExample: "Med Spa",
    animation: "grow-right",
    defaultContent: content("Treatment Mix", "Consults grouped by intent", stackedRows(["Botox", "Laser", "Facial"], ["New", "Returning", "Member"])),
    createOptions: (ctx) => bar({coordinate: {transform: [{type: "transpose"}]}, transform: [{type: "stackY"}], labels: undefined})(ctx),
  },
  {
    engine: "g2",
    id: "g2-lead-source-share",
    name: "Lead Source Share",
    category: "Breakdown",
    description: "Normalized share bars for channel contribution.",
    industryExample: "Attorney",
    animation: "grow-right",
    defaultContent: content("Lead Source Share", "Share of new qualified inquiries", stackedRows(["Search", "Referral", "Social"], ["Calls", "Forms", "Chats"])),
    createOptions: (ctx) => bar({coordinate: {transform: [{type: "transpose"}]}, transform: [{type: "stackY"}, {type: "normalizeY"}], labels: undefined})(ctx),
  },
  {
    engine: "g2",
    id: "g2-monthly-performance",
    name: "Monthly Performance",
    category: "Trend",
    description: "Vertical columns for monthly business activity.",
    industryExample: "Chiropractor",
    animation: "grow-up",
    supportsAddRemove: true,
    defaultContent: content("Monthly Performance", "New patient exams booked", [
      row("jan", "Jan", 24), row("feb", "Feb", 29), row("mar", "Mar", 35), row("apr", "Apr", 31), row("may", "May", 42), row("jun", "Jun", 47),
    ]),
    createOptions: (ctx) => bar({labels: labels(ctx, "top")})(ctx),
  },
  {
    engine: "g2",
    id: "g2-channel-comparison",
    name: "Channel Comparison",
    category: "Comparison",
    description: "Grouped columns for comparing campaigns across channels.",
    industryExample: "Personal Trainer",
    animation: "grow-up",
    defaultContent: content("Channel Comparison", "Trial sessions by source", [
      row("ig-a", "Instagram", 18, "Week 1"), row("ig-b", "Instagram", 25, "Week 2"),
      row("ref-a", "Referral", 13, "Week 1"), row("ref-b", "Referral", 19, "Week 2"),
      row("web-a", "Website", 16, "Week 1"), row("web-b", "Website", 21, "Week 2"),
    ]),
    createOptions: (ctx) => bar({transform: [{type: "dodgeX"}], labels: labels(ctx, "top")})(ctx),
  },
  {
    engine: "g2",
    id: "g2-pipeline-breakdown",
    name: "Pipeline Breakdown",
    category: "Breakdown",
    description: "Stacked columns for pipeline stages over time.",
    industryExample: "Realtor",
    animation: "grow-up",
    defaultContent: content("Pipeline Breakdown", "Buyer pipeline by stage", stackedRows(["Jan", "Feb", "Mar", "Apr"], ["Tours", "Offers", "Closings"])),
    createOptions: bar({transform: [{type: "stackY"}], labels: undefined}),
  },
  {
    engine: "g2",
    id: "g2-result-waterfall",
    name: "Result Breakdown",
    category: "Breakdown",
    description: "Waterfall-style result ladder for explaining net change.",
    industryExample: "Attorney",
    animation: "grow-up",
    defaultContent: content("Result Breakdown", "Net new signed matters", [row("start", "Starting", 22), row("ref", "Referrals", 14), row("ads", "Ads", 9), row("lost", "Lost", -6), row("signed", "Signed", 39)]),
    createOptions: (ctx) => bar({encode: {x: "label", y: "value", color: "group"}, labels: labels(ctx, "top")})(ctx),
  },
  {
    engine: "g2",
    id: "g2-goal-tracker",
    name: "Goal Tracker",
    category: "KPI",
    description: "Bullet-style goal tracker for targets.",
    industryExample: "Med Spa",
    animation: "grow-right",
    defaultContent: content("Goal Tracker", "Monthly booking progress by offer", [
      row("m1", "Injectables", 74, "Actual", undefined, 90),
      row("m2", "Facials", 58, "Actual", undefined, 70),
      row("m3", "Laser", 44, "Actual", undefined, 60),
    ]),
    createOptions: (ctx) => bar({coordinate: {transform: [{type: "transpose"}]}, labels: labels(ctx)})(ctx),
  },
  {
    engine: "g2",
    id: "g2-basic-growth",
    name: "Monthly Growth",
    category: "Trend",
    description: "Clean line chart for steady growth stories.",
    industryExample: "Dentist",
    animation: "path-style-reveal",
    supportsAddRemove: true,
    defaultContent: content("Monthly Growth", "Hygiene rebooks over six months", [row("jan", "Jan", 31), row("feb", "Feb", 35), row("mar", "Mar", 38), row("apr", "Apr", 44), row("may", "May", 46), row("jun", "Jun", 52)]),
    createOptions: (ctx) => ({...base(ctx), type: "line", encode: {x: "label", y: "value"}, style: {stroke: studioTheme.gold, lineWidth: 4}, labels: labels(ctx, "top")} as G2Spec),
  },
  {
    engine: "g2",
    id: "g2-multi-line",
    name: "Campaign Lineup",
    category: "Trend",
    description: "Multi-series line comparison for content campaigns.",
    industryExample: "Personal Trainer",
    animation: "path-style-reveal",
    defaultContent: content("Campaign Lineup", "Weekly trial bookings", stackedRows(["W1", "W2", "W3", "W4"], ["Instagram", "Referral", "Search"])),
    createOptions: (ctx) => ({...base(ctx), type: "line", encode: {x: "label", y: "value", color: "group"}, style: {lineWidth: 3}, labels: undefined} as G2Spec),
  },
  {
    engine: "g2",
    id: "g2-smooth-trend",
    name: "Smooth Trend",
    category: "Trend",
    description: "Smoothed line for a polished growth signal.",
    industryExample: "Chiropractor",
    animation: "path-style-reveal",
    defaultContent: content("Smooth Trend", "Care plan starts", [row("jan", "Jan", 12), row("feb", "Feb", 15), row("mar", "Mar", 21), row("apr", "Apr", 20), row("may", "May", 28), row("jun", "Jun", 33)]),
    createOptions: (ctx) => ({...base(ctx), type: "line", encode: {x: "label", y: "value"}, shape: "smooth", style: {stroke: studioTheme.goldSoft, lineWidth: 4}, labels: labels(ctx, "top")} as G2Spec),
  },
  {
    engine: "g2",
    id: "g2-area-growth",
    name: "Area Growth",
    category: "Trend",
    description: "Area growth chart for building momentum.",
    industryExample: "Realtor",
    animation: "grow-up",
    defaultContent: content("Area Growth", "Listing conversations created", [row("jan", "Jan", 14), row("feb", "Feb", 22), row("mar", "Mar", 25), row("apr", "Apr", 33), row("may", "May", 38), row("jun", "Jun", 44)]),
    createOptions: (ctx) => ({...base(ctx), type: "area", encode: {x: "label", y: "value"}, style: {fill: "linear-gradient(-90deg, rgba(216,173,85,0.12) 0%, rgba(216,173,85,0.72) 100%)"}} as G2Spec),
  },
  {
    engine: "g2",
    id: "g2-stacked-area",
    name: "Source Composition",
    category: "Trend",
    description: "Stacked area for source mix over time.",
    industryExample: "Attorney",
    animation: "grow-up",
    defaultContent: content("Source Composition", "Signed matters by source", stackedRows(["Jan", "Feb", "Mar", "Apr", "May"], ["Referral", "Search", "Social"])),
    createOptions: (ctx) => ({...base(ctx), type: "area", encode: {x: "label", y: "value", color: "group"}, transform: [{type: "stackY"}], labels: undefined} as G2Spec),
  },
  {
    engine: "g2",
    id: "g2-donut-breakdown",
    name: "Lead Source Breakdown",
    category: "Breakdown",
    description: "Donut breakdown for source or service composition.",
    industryExample: "Dentist",
    animation: "radial-reveal",
    supportsAddRemove: true,
    defaultContent: content("Lead Source Breakdown", "New patient sources", [row("search", "Search", 42), row("ref", "Referral", 30), row("social", "Social", 18), row("walk", "Walk-in", 10)]),
    createOptions: (ctx) => ({...base(ctx), type: "interval", coordinate: {type: "theta", innerRadius: 0.58}, encode: {y: "value", color: "label"}, axis: false, labels: ctx.controls.showLabels ? [{text: "label", position: "outside", fill: studioTheme.text}] : undefined} as G2Spec),
  },
  {
    engine: "g2",
    id: "g2-labeled-pie",
    name: "Service Mix Pie",
    category: "Breakdown",
    description: "Labeled pie for simple proportional stories.",
    industryExample: "Med Spa",
    animation: "radial-reveal",
    defaultContent: content("Service Mix", "Booked appointments by service", [row("botox", "Botox", 36), row("laser", "Laser", 24), row("facial", "Facial", 28), row("body", "Body", 12)]),
    createOptions: (ctx) => ({...base(ctx), type: "interval", coordinate: {type: "theta"}, encode: {y: "value", color: "label"}, axis: false, labels: ctx.controls.showLabels ? [{text: "label", position: "outside", fill: studioTheme.text}] : undefined} as G2Spec),
  },
  {
    engine: "g2",
    id: "g2-rose-comparison",
    name: "Category Rose",
    category: "Comparison",
    description: "Rose chart for bold category comparison.",
    industryExample: "Personal Trainer",
    animation: "radial-reveal",
    defaultContent: content("Category Rose", "Client goals selected this month", [row("fat", "Fat loss", 42), row("strength", "Strength", 35), row("mobility", "Mobility", 21), row("energy", "Energy", 28)]),
    createOptions: (ctx) => ({...base(ctx), type: "interval", coordinate: {type: "polar"}, encode: {x: "label", y: "value", color: "label"}, axis: false, labels: labels(ctx, "outside")} as G2Spec),
  },
  {
    engine: "g2",
    id: "g2-radial-progress",
    name: "Radial Progress",
    category: "KPI",
    description: "Radial progress for a single headline target.",
    industryExample: "Chiropractor",
    animation: "radial-reveal",
    defaultContent: content("Radial Progress", "Wellness visit target reached", [row("progress", "Reached", 78), row("remaining", "Remaining", 22)]),
    createOptions: (ctx) => ({...base(ctx), type: "interval", coordinate: {type: "theta", innerRadius: 0.72, startAngle: -Math.PI / 2, endAngle: Math.PI * 1.5}, encode: {y: "value", color: "label"}, axis: false, labels: ctx.controls.showLabels ? [{text: "value", fill: studioTheme.text}] : undefined} as G2Spec),
  },
  {
    engine: "g2",
    id: "g2-gauge-achievement",
    name: "Goal Achievement",
    category: "KPI",
    description: "Gauge-style achievement readout.",
    industryExample: "Attorney",
    animation: "radial-reveal",
    defaultContent: content("Goal Achievement", "Consult goal completion", [row("done", "Booked", 68), row("left", "Open", 32)]),
    createOptions: (ctx) => ({...base(ctx), type: "interval", coordinate: {type: "theta", innerRadius: 0.68, startAngle: -Math.PI, endAngle: 0}, encode: {y: "value", color: "label"}, axis: false, labels: ctx.controls.showLabels ? [{text: "label", fill: studioTheme.text}] : undefined} as G2Spec),
  },
  {
    engine: "g2",
    id: "g2-conversion-funnel",
    name: "Conversion Funnel",
    category: "Funnel",
    description: "Funnel-inspired ranked bars for conversion stages.",
    industryExample: "Med Spa",
    animation: "grow-right",
    defaultContent: content("Conversion Funnel", "Consult path from lead to member", [row("reach", "Reached", 100), row("inquire", "Inquired", 62), row("consult", "Consulted", 38), row("book", "Booked", 24)]),
    createOptions: (ctx) => bar({coordinate: {transform: [{type: "transpose"}]}, style: {radius: 7}, labels: labels(ctx)})(ctx),
  },
  {
    engine: "g2",
    id: "g2-pyramid-stages",
    name: "Client Journey Pyramid",
    category: "Funnel",
    description: "Pyramid-style stages for awareness-to-retention stories.",
    industryExample: "Personal Trainer",
    animation: "grow-up",
    defaultContent: content("Client Journey Pyramid", "From trial to renewal", [row("aware", "Awareness", 96), row("trial", "Trial", 54), row("start", "Starts", 29), row("renew", "Renews", 18)]),
    createOptions: (ctx) => bar({coordinate: {transform: [{type: "transpose"}]}, style: {radius: 3}, labels: labels(ctx)})(ctx),
  },
  {
    engine: "g2",
    id: "g2-radar-comparison",
    name: "Performance Radar",
    category: "Comparison",
    description: "Radar comparison for balanced score snapshots.",
    industryExample: "Dentist",
    animation: "radial-reveal",
    defaultContent: content("Performance Radar", "Office strengths by operating area", [row("reviews", "Reviews", 82), row("rebook", "Rebook", 76), row("hygiene", "Hygiene", 88), row("case", "Case Accept", 63), row("speed", "Speed", 70)]),
    createOptions: (ctx) => ({...base(ctx), type: "line", coordinate: {type: "polar"}, encode: {x: "label", y: "value"}, style: {stroke: studioTheme.gold, lineWidth: 3}, labels: labels(ctx, "top")} as G2Spec),
  },
  {
    engine: "g2",
    id: "g2-scatter-relationship",
    name: "Relationship Map",
    category: "Relationship",
    description: "Scatter relationship for effort and result comparisons.",
    industryExample: "Realtor",
    animation: "fade-scale",
    defaultContent: content("Relationship Map", "Touchpoints compared with listing appointments", [row("social", "Social", 35, "Online", 12), row("email", "Email", 24, "Owned", 8), row("calls", "Calls", 18, "Direct", 15), row("events", "Events", 28, "Local", 19)]),
    createOptions: (ctx) => ({...base(ctx), type: "point", encode: {x: "value", y: "secondaryValue", color: "group", size: "value"}, labels: ctx.controls.showLabels ? [{text: "label", fill: studioTheme.text, dy: -10}] : undefined} as G2Spec),
  },
  {
    engine: "g2",
    id: "g2-kpi-sparkline",
    name: "Performance Snapshot",
    category: "KPI",
    description: "KPI plus sparkline-style trend for social content cards.",
    industryExample: "Chiropractor",
    animation: "path-style-reveal",
    defaultContent: content("Performance Snapshot", "Exam bookings are up week over week", [row("w1", "W1", 18), row("w2", "W2", 21), row("w3", "W3", 20), row("w4", "W4", 29), row("w5", "W5", 34)]),
    createOptions: (ctx) => ({...base(ctx), type: "line", encode: {x: "label", y: "value"}, axis: false, style: {stroke: studioTheme.goldSoft, lineWidth: 5}, labels: ctx.controls.showLabels ? [{text: "value", position: "top", fill: studioTheme.text}] : undefined} as G2Spec),
  },
]);
