export type ProductTemplateId =
  | "obsidian"
  | "gallery"
  | "kinetic"
  | "aura"
  | "editorial"
  | "precision"
  | "monument"
  | "chromatic"
  | "launch"
  | "essential"
  | "eclipse"
  | "swiss"
  | "type-impact"
  | "triptych"
  | "liquid"
  | "blueprint"
  | "pop-tile"
  | "pedestal"
  | "countdown"
  | "scrapbook"
  | "prism"
  | "material-study"
  | "performance-tunnel"
  | "luxury-catalogue"
  | "color-lab"
  | "unboxing"
  | "feature-orbit"
  | "cinematic-scale"
  | "retail-window"
  | "campaign-finale"
  | "shadow-signature"
  | "product-chorus"
  | "runway-track"
  | "broadcast-performance"
  | "object-passport"
  | "conveyor-drop"
  | "botanical-form"
  | "type-sculpture"
  | "mirror-sequence"
  | "one-take"
  | "glasshouse"
  | "precision-slice"
  | "macro-cinema"
  | "gravity-field"
  | "chromatic-signal"
  | "museum-after-dark"
  | "paper-engineering"
  | "lightbox-sequence"
  | "analog-campaign"
  | "brand-takeover"
  | "motion-control"
  | "noir-chamber"
  | "golden-hour"
  | "arctic-vault"
  | "ember-forge"
  | "neon-rain"
  | "tidal-light"
  | "desert-monument"
  | "celestial-event"
  | "directors-cut"
  | "luxury-object"
  | "beauty-ritual"
  | "performance-engine"
  | "technology-keynote"
  | "tabletop-appetite"
  | "fashion-campaign"
  | "home-editorial"
  | "outdoor-proven"
  | "retail-impact"
  | "future-essential"
  | "angle-study"
  | "detail-proof"
  | "product-in-context"
  | "live-demonstration"
  | "before-after"
  | "colorway-collection"
  | "package-to-product"
  | "feature-in-focus"
  | "human-moment"
  | "campaign-cut"
  | "curtain-call"
  | "stage-flats"
  | "frame-step"
  | "projection-room"
  | "silhouette-trace"
  | "object-choreography"
  | "five-beat-film"
  | "worlds-around-object"
  | "living-still"
  | "tension-release"
  | "reverse-reveal"
  | "false-ending"
  | "dual-timeline"
  | "flashbulb-editorial"
  | "invisible-cut"
  | "speed-ramp"
  | "call-response"
  | "the-interruption"
  | "palindrome"
  | "the-callback"
  | "frame-magnet"
  | "negative-space"
  | "scale-relay"
  | "blindside"
  | "counterweight"
  | "echo-exit"
  | "wordmark-passage"
  | "still-point"
  | "contour-cut"
  | "last-one-standing"
  | "material-noir"
  | "mineral-gallery"
  | "wet-asphalt"
  | "travertine-sun"
  | "brushed-alloy"
  | "paper-atelier"
  | "concrete-runway"
  | "velvet-chamber"
  | "timber-ritual"
  | "studio-archive";

export type ProductMediaSlotId =
  | "hero"
  | "angleSide"
  | "angleThreeQuarter"
  | "detailOne"
  | "detailTwo"
  | "lifestyleImage"
  | "demoVideo"
  | "beforeImage"
  | "afterImage"
  | "variantTwo"
  | "variantThree"
  | "packageImage"
  | "unpackedImage"
  | "featureOne"
  | "featureTwo"
  | "lifestyleVideo"
  | "campaignImage"
  | "campaignVideo";

export type ProductMediaSlot = {
  id: ProductMediaSlotId;
  label: string;
  kind: "image" | "video";
  removeBackground?: boolean;
};

export type ProductTemplate = {
  id: ProductTemplateId;
  name: string;
  category: string;
  description: string;
  batch: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
  accent: string;
  background: string;
  surface: string;
  foreground: string;
  muted: string;
  layout:
    | "split"
    | "center"
    | "poster"
    | "editorial"
    | "technical";
  imageFit: "contain" | "cover";
  imageScale: number;
  eyebrow: string;
  headline: string;
  subheadline: string;
  cta: string;
  polyHavenDefaultAssetId?: string;
  mediaSlots?: ProductMediaSlot[];
};

export const productTemplates: ProductTemplate[] = [
  {
    id: "obsidian",
    name: "Obsidian Reveal",
    category: "Luxury",
    description: "Dark cinematic launch with a focused product reveal.",
    batch: 1,
    accent: "#d8ad55",
    background: "#090909",
    surface: "#141414",
    foreground: "#f7f3ea",
    muted: "#aaa49a",
    layout: "split",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "THE NEW STANDARD",
    headline: "Designed to be unforgettable.",
    subheadline: "Precision, presence, and performance in one defining product.",
    cta: "Discover now",
  },
  {
    id: "gallery",
    name: "Gallery White",
    category: "Minimal",
    description: "Museum-clean composition for premium consumer products.",
    batch: 1,
    accent: "#111111",
    background: "#f3f0e9",
    surface: "#ffffff",
    foreground: "#111111",
    muted: "#6e6a62",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.88,
    eyebrow: "INTRODUCING",
    headline: "Less noise. More product.",
    subheadline: "A refined object deserves a clear stage.",
    cta: "See the details",
  },
  {
    id: "kinetic",
    name: "Kinetic Grid",
    category: "Technology",
    description: "High-energy modular system for devices and innovation.",
    batch: 1,
    accent: "#7c5cff",
    background: "#0b0c12",
    surface: "#171924",
    foreground: "#ffffff",
    muted: "#a9abc0",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "ENGINEERED FOR MORE",
    headline: "Power, precisely placed.",
    subheadline: "Every detail calibrated for speed and control.",
    cta: "Explore performance",
  },
  {
    id: "aura",
    name: "Aura Bloom",
    category: "Beauty",
    description: "Soft luminous launch for skincare, fragrance, and wellness.",
    batch: 1,
    accent: "#ff7ca8",
    background: "#220f1d",
    surface: "#38182e",
    foreground: "#fff5f8",
    muted: "#dfb8c8",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "MEET YOUR NEW RITUAL",
    headline: "A glow that starts within.",
    subheadline: "An elevated essential made for everyday radiance.",
    cta: "Experience the ritual",
  },
  {
    id: "editorial",
    name: "Editorial Cut",
    category: "Fashion",
    description: "Bold magazine typography with an art-directed product crop.",
    batch: 1,
    accent: "#f04424",
    background: "#e8e1d4",
    surface: "#d4c8b6",
    foreground: "#15130f",
    muted: "#625c53",
    layout: "editorial",
    imageFit: "cover",
    imageScale: 1,
    eyebrow: "THE EDIT",
    headline: "Made to move differently.",
    subheadline: "A new silhouette for the moments that matter.",
    cta: "Shop the edit",
  },
  {
    id: "precision",
    name: "Precision Lab",
    category: "Performance",
    description: "Technical storytelling for engineered and performance goods.",
    batch: 1,
    accent: "#9ef01a",
    background: "#08100c",
    surface: "#111d16",
    foreground: "#ecf7ef",
    muted: "#9bad9f",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.86,
    eyebrow: "BUILT WITHOUT COMPROMISE",
    headline: "Performance you can measure.",
    subheadline: "Advanced materials. Purposeful geometry. Proven results.",
    cta: "View specifications",
  },
  {
    id: "monument",
    name: "Monument",
    category: "Iconic",
    description: "Heroic centered composition that makes one object feel iconic.",
    batch: 1,
    accent: "#ffcf33",
    background: "#15110b",
    surface: "#241d12",
    foreground: "#fff8e8",
    muted: "#c9bfa9",
    layout: "poster",
    imageFit: "contain",
    imageScale: 1,
    eyebrow: "ONE OBJECT. TOTAL PRESENCE.",
    headline: "Meet the icon.",
    subheadline: "Created for those who recognize the exceptional.",
    cta: "Own the moment",
  },
  {
    id: "chromatic",
    name: "Chromatic Pop",
    category: "Social",
    description: "Bold color, oversized type, and playful product movement.",
    batch: 1,
    accent: "#081018",
    background: "#35e0ff",
    surface: "#f8ff46",
    foreground: "#081018",
    muted: "#254551",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.88,
    eyebrow: "JUST DROPPED",
    headline: "Make ordinary impossible.",
    subheadline: "The product built to stand out everywhere.",
    cta: "Get yours",
  },
  {
    id: "launch",
    name: "Launch Signal",
    category: "Campaign",
    description: "Conversion-focused launch narrative with proof-point pacing.",
    batch: 1,
    accent: "#ff5b3d",
    background: "#0e1118",
    surface: "#1a1f2b",
    foreground: "#ffffff",
    muted: "#a9b0c1",
    layout: "split",
    imageFit: "contain",
    imageScale: 0.88,
    eyebrow: "AVAILABLE NOW",
    headline: "The wait is over.",
    subheadline: "A breakthrough product, ready for its first impression.",
    cta: "Launch your order",
  },
  {
    id: "essential",
    name: "Everyday Essential",
    category: "Lifestyle",
    description: "Warm, approachable product storytelling for everyday goods.",
    batch: 1,
    accent: "#1d5d4d",
    background: "#eee6d8",
    surface: "#fbf7ef",
    foreground: "#18352e",
    muted: "#647d75",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.88,
    eyebrow: "BETTER BY DESIGN",
    headline: "Made for every day.",
    subheadline: "Thoughtful details that make the familiar feel exceptional.",
    cta: "Find your essential",
  },
  {
    id: "eclipse",
    name: "Eclipse Luxury",
    category: "Luxury",
    description: "A restrained rim-light reveal for premium objects.",
    batch: 2,
    accent: "#d7b56d",
    background: "#030303",
    surface: "#15120d",
    foreground: "#f7f0df",
    muted: "#a89f8d",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "AN OBJECT OF DISTINCTION",
    headline: "Presence, revealed.",
    subheadline: "Crafted for the moment everything else falls away.",
    cta: "Discover the collection",
  },
  {
    id: "swiss",
    name: "Swiss Specification",
    category: "Precision",
    description: "A rigorous modular product story with measured detail.",
    batch: 2,
    accent: "#ff3b30",
    background: "#f1f0eb",
    surface: "#ffffff",
    foreground: "#111111",
    muted: "#666660",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.88,
    eyebrow: "FORM / FUNCTION / DETAIL",
    headline: "Built with intent.",
    subheadline: "Every line considered. Every detail working harder.",
    cta: "View the system",
  },
  {
    id: "type-impact",
    name: "Type Impact",
    category: "Culture",
    description: "Oversized kinetic typography built around the product.",
    batch: 2,
    accent: "#ffea00",
    background: "#ef2b2d",
    surface: "#101010",
    foreground: "#ffffff",
    muted: "#ffd4cf",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "NO QUIET ENTRANCES",
    headline: "Made to hit different.",
    subheadline: "One product. Maximum signal.",
    cta: "Make it yours",
  },
  {
    id: "triptych",
    name: "Editorial Triptych",
    category: "Editorial",
    description: "Three art-directed crops resolve into one hero image.",
    batch: 2,
    accent: "#bf2b21",
    background: "#ded7c8",
    surface: "#f6f1e7",
    foreground: "#171513",
    muted: "#665e55",
    layout: "editorial",
    imageFit: "cover",
    imageScale: 1,
    eyebrow: "THE OBJECT / THREE VIEWS",
    headline: "Every angle has a point of view.",
    subheadline: "A study in proportion, texture, and character.",
    cta: "See every detail",
  },
  {
    id: "liquid",
    name: "Liquid Bloom",
    category: "Beauty",
    description: "Organic color fields carry a soft floating product reveal.",
    batch: 2,
    accent: "#ff8ab7",
    background: "#fff0f4",
    surface: "#e7c5ff",
    foreground: "#3c1430",
    muted: "#825f78",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "A NEW DAILY RITUAL",
    headline: "Made to feel luminous.",
    subheadline: "A softer approach to everyday transformation.",
    cta: "Begin the ritual",
  },
  {
    id: "blueprint",
    name: "Blueprint Breakdown",
    category: "Engineering",
    description: "Technical callouts map the product before a clean hero finish.",
    batch: 2,
    accent: "#5ee7ff",
    background: "#06192b",
    surface: "#0c2d49",
    foreground: "#e8faff",
    muted: "#8cb8c7",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.86,
    eyebrow: "DESIGNED FROM THE INSIDE OUT",
    headline: "Every detail earns its place.",
    subheadline: "Material, geometry, and performance in one complete system.",
    cta: "Explore the build",
  },
  {
    id: "pop-tile",
    name: "Pop Tile Motion",
    category: "Social",
    description: "A rhythmic color grid turns one product into a visual hook.",
    batch: 2,
    accent: "#ff4d00",
    background: "#ffe600",
    surface: "#5d3bff",
    foreground: "#111111",
    muted: "#4d3d18",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.86,
    eyebrow: "NEW / NOW / EVERYWHERE",
    headline: "Too good to scroll past.",
    subheadline: "Color, character, and instant recognition.",
    cta: "Get it now",
  },
  {
    id: "pedestal",
    name: "Gallery Pedestal",
    category: "Showroom",
    description: "An architectural stage elevates the product into an exhibit.",
    batch: 2,
    accent: "#b69b73",
    background: "#d8d1c5",
    surface: "#eee9e1",
    foreground: "#28241f",
    muted: "#736b61",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "COLLECTION NO. 01",
    headline: "Designed for the room.",
    subheadline: "A singular object with architectural presence.",
    cta: "Enter the gallery",
  },
  {
    id: "countdown",
    name: "Launch Countdown",
    category: "Campaign",
    description: "A signal-driven countdown lands on a decisive product reveal.",
    batch: 2,
    accent: "#ff4b35",
    background: "#080b12",
    surface: "#171c29",
    foreground: "#ffffff",
    muted: "#9ba4b5",
    layout: "split",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "THE DROP IS LIVE",
    headline: "Your wait ends now.",
    subheadline: "The next release has officially arrived.",
    cta: "Secure yours",
  },
  {
    id: "scrapbook",
    name: "Lifestyle Scrapbook",
    category: "Lifestyle",
    description: "Layered paper, labels, and product cutouts create a tactile story.",
    batch: 2,
    accent: "#f06b4f",
    background: "#f3e7cc",
    surface: "#fffaf0",
    foreground: "#24362d",
    muted: "#6c776f",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.88,
    eyebrow: "THE EVERYDAY EDIT",
    headline: "Good design lives with you.",
    subheadline: "Thoughtful, useful, and ready for real life.",
    cta: "Bring it home",
  },
  {
    id: "prism",
    name: "Prism Chamber",
    category: "Future Luxury",
    description: "Refracted light planes build a dimensional premium reveal.",
    batch: 3,
    accent: "#8cf5ff",
    background: "#05060c",
    surface: "#17152e",
    foreground: "#f7fbff",
    muted: "#9ca9bd",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "LIGHT / FORM / PRESENCE",
    headline: "See it in a new light.",
    subheadline: "A precise object, revealed through color and dimension.",
    cta: "Enter the prism",
  },
  {
    id: "material-study",
    name: "Material Study",
    category: "Craft",
    description: "Tactile macro panels assemble into a complete product portrait.",
    batch: 3,
    accent: "#c66b3d",
    background: "#ded4c5",
    surface: "#f6f0e7",
    foreground: "#211b17",
    muted: "#74685e",
    layout: "editorial",
    imageFit: "cover",
    imageScale: 1,
    eyebrow: "A STUDY IN MATERIAL",
    headline: "Made to be felt.",
    subheadline: "Texture, finish, and form come together with intention.",
    cta: "Explore the craft",
  },
  {
    id: "performance-tunnel",
    name: "Performance Tunnel",
    category: "Performance",
    description: "Accelerating perspective and telemetry frame a high-speed launch.",
    batch: 3,
    accent: "#c8ff32",
    background: "#030705",
    surface: "#142116",
    foreground: "#f5ffe9",
    muted: "#91a190",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "PERFORMANCE / UNLOCKED",
    headline: "Built for momentum.",
    subheadline: "Every system tuned to move faster, further, and with control.",
    cta: "See the performance",
  },
  {
    id: "luxury-catalogue",
    name: "Luxury Catalogue",
    category: "Fashion",
    description: "A numbered editorial edition with refined page-turn pacing.",
    batch: 3,
    accent: "#811f24",
    background: "#e9e2d6",
    surface: "#faf7f1",
    foreground: "#161310",
    muted: "#6d655c",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "THE PRIVATE EDITION",
    headline: "An object worth collecting.",
    subheadline: "Considered proportions. Lasting character. Singular presence.",
    cta: "View the edition",
  },
  {
    id: "color-lab",
    name: "Color Laboratory",
    category: "Color",
    description: "Controlled color fields transform around a pristine hero object.",
    batch: 3,
    accent: "#ff4f9a",
    background: "#ffdf3e",
    surface: "#6057ff",
    foreground: "#111019",
    muted: "#493f3c",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "COLOR / COMPOSITION / YOU",
    headline: "Choose your energy.",
    subheadline: "One unmistakable design, expressed in full color.",
    cta: "Find your color",
  },
  {
    id: "unboxing",
    name: "Unboxing Ceremony",
    category: "Reveal",
    description: "Layered packaging doors create anticipation before the hero reveal.",
    batch: 3,
    accent: "#d5b174",
    background: "#15110d",
    surface: "#2a221a",
    foreground: "#fff8eb",
    muted: "#b7aa98",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "THE ARRIVAL",
    headline: "Worth the anticipation.",
    subheadline: "Every layer considered. Every detail waiting to be discovered.",
    cta: "Open the experience",
  },
  {
    id: "feature-orbit",
    name: "Feature Orbit",
    category: "Technology",
    description: "Structured feature satellites revolve around a centered product.",
    batch: 3,
    accent: "#5ee6ff",
    background: "#07101f",
    surface: "#112445",
    foreground: "#f1f8ff",
    muted: "#8ba1bd",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.86,
    eyebrow: "THE COMPLETE SYSTEM",
    headline: "Everything works together.",
    subheadline: "Core performance surrounded by the features that make it exceptional.",
    cta: "Explore every feature",
  },
  {
    id: "cinematic-scale",
    name: "Cinematic Scale",
    category: "Icon",
    description: "Extreme cinematic crops pull back into a monumental hero frame.",
    batch: 3,
    accent: "#f3c45c",
    background: "#070707",
    surface: "#1a1813",
    foreground: "#fffaf0",
    muted: "#aaa398",
    layout: "poster",
    imageFit: "contain",
    imageScale: 1,
    eyebrow: "BUILT LARGER THAN LIFE",
    headline: "Impossible to overlook.",
    subheadline: "A defining object deserves a cinematic introduction.",
    cta: "Meet the icon",
  },
  {
    id: "retail-window",
    name: "Retail Window",
    category: "Retail",
    description: "A dimensional storefront display turns the product into the destination.",
    batch: 3,
    accent: "#ff735c",
    background: "#d6e7e1",
    surface: "#fff8ee",
    foreground: "#16322f",
    muted: "#627772",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "NOW IN THE WINDOW",
    headline: "Stop. Look. Want.",
    subheadline: "A display designed to turn attention into desire.",
    cta: "Shop the window",
  },
  {
    id: "campaign-finale",
    name: "Campaign Finale",
    category: "Campaign",
    description: "A rapid campaign montage resolves into one decisive brand frame.",
    batch: 3,
    accent: "#ff3d26",
    background: "#0b0b0c",
    surface: "#f2eee6",
    foreground: "#ffffff",
    muted: "#b4b1ac",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "THIS IS THE MOMENT",
    headline: "The campaign starts now.",
    subheadline: "One product. One signal. One unforgettable final frame.",
    cta: "Make it yours",
  },
  {
    id: "shadow-signature",
    name: "Shadow Signature",
    category: "Monochrome",
    description: "A fashion-led silhouette becomes a precise product portrait.",
    batch: 4,
    accent: "#f5f1e8",
    background: "#050505",
    surface: "#1a1a1a",
    foreground: "#faf8f3",
    muted: "#aaa7a0",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "FORM LEAVES A SIGNATURE",
    headline: "Recognized before it is revealed.",
    subheadline: "A silhouette with nothing accidental about it.",
    cta: "Discover the form",
  },
  {
    id: "product-chorus",
    name: "Product Chorus",
    category: "Rhythm",
    description: "A synchronized field of products resolves into one unmistakable hero.",
    batch: 4,
    accent: "#ffdb21",
    background: "#ff5f45",
    surface: "#1e4bff",
    foreground: "#111111",
    muted: "#542b27",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.86,
    eyebrow: "ONE DESIGN / EVERYWHERE",
    headline: "One becomes the movement.",
    subheadline: "Repeated, recognized, and impossible to miss.",
    cta: "Join the chorus",
  },
  {
    id: "runway-track",
    name: "Runway Track",
    category: "Fashion Motion",
    description: "A lateral tracking sequence presents the product like a runway arrival.",
    batch: 4,
    accent: "#ef3849",
    background: "#eee9df",
    surface: "#171717",
    foreground: "#141414",
    muted: "#6d675f",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "THE ARRIVAL / LOOK 01",
    headline: "Made for the entrance.",
    subheadline: "A defining silhouette, moving with complete confidence.",
    cta: "See the collection",
  },
  {
    id: "broadcast-performance",
    name: "Broadcast Performance",
    category: "Sport",
    description: "Score graphics and replay crops frame the product as an elite performer.",
    batch: 4,
    accent: "#ffef36",
    background: "#061c32",
    surface: "#0f4d79",
    foreground: "#ffffff",
    muted: "#9ab4c8",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "LIVE / PERFORMANCE FEED",
    headline: "Built to lead the field.",
    subheadline: "Measured under pressure. Designed to perform beyond it.",
    cta: "View the replay",
  },
  {
    id: "object-passport",
    name: "Object Passport",
    category: "Archive",
    description: "Serial marks, inspection fields, and provenance build a collectible dossier.",
    batch: 4,
    accent: "#c83e2f",
    background: "#d8cfbb",
    surface: "#f2ead7",
    foreground: "#27231c",
    muted: "#756c5c",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.88,
    eyebrow: "OBJECT / VERIFIED / ORIGINAL",
    headline: "Identity, documented.",
    subheadline: "Origin, material, and intention recorded in one defining object.",
    cta: "Inspect the record",
  },
  {
    id: "conveyor-drop",
    name: "Conveyor Drop",
    category: "Release",
    description: "A graphic product stream selects and elevates the next release.",
    batch: 4,
    accent: "#ff583d",
    background: "#ece9df",
    surface: "#202125",
    foreground: "#151515",
    muted: "#696963",
    layout: "split",
    imageFit: "contain",
    imageScale: 0.86,
    eyebrow: "DROP LINE / ITEM SELECTED",
    headline: "This one is yours.",
    subheadline: "The release has arrived. The next move belongs to you.",
    cta: "Claim the drop",
  },
  {
    id: "botanical-form",
    name: "Botanical Form",
    category: "Natural Luxury",
    description: "Graphic foliage and living shadows create a restrained organic campaign.",
    batch: 4,
    accent: "#b5cf73",
    background: "#e8e2cf",
    surface: "#315746",
    foreground: "#173128",
    muted: "#64746b",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "DESIGNED WITH NATURE IN MIND",
    headline: "A more natural essential.",
    subheadline: "Purposeful form grounded in a softer way of living.",
    cta: "Return to nature",
  },
  {
    id: "type-sculpture",
    name: "Type Sculpture",
    category: "Typography",
    description: "Monumental letterforms mask and physically frame the product.",
    batch: 4,
    accent: "#ff4738",
    background: "#f2ede3",
    surface: "#151515",
    foreground: "#111111",
    muted: "#6c665d",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "OBJECT MEETS LANGUAGE",
    headline: "The product is the statement.",
    subheadline: "Form and message become one unmistakable composition.",
    cta: "Read the object",
  },
  {
    id: "mirror-sequence",
    name: "Mirror Sequence",
    category: "Reflective Luxury",
    description: "Choreographed reflections create a premium installation around the product.",
    batch: 4,
    accent: "#b8c8ff",
    background: "#080917",
    surface: "#20284a",
    foreground: "#f5f6ff",
    muted: "#9a9fbd",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "EVERY ANGLE / ONE IDENTITY",
    headline: "Reflection becomes presence.",
    subheadline: "A singular design, multiplied through light and perspective.",
    cta: "See every angle",
  },
  {
    id: "one-take",
    name: "One-Take Reveal",
    category: "Cinema",
    description: "A continuous virtual camera move travels from detail to full campaign frame.",
    batch: 4,
    accent: "#d8a449",
    background: "#090909",
    surface: "#211a11",
    foreground: "#fffaf1",
    muted: "#aaa196",
    layout: "poster",
    imageFit: "contain",
    imageScale: 1,
    eyebrow: "ONE SHOT / NO INTERRUPTIONS",
    headline: "Stay with the moment.",
    subheadline: "From the smallest detail to the complete object in one continuous move.",
    cta: "Watch it unfold",
  },
  {
    id: "glasshouse",
    name: "Glasshouse",
    category: "Spatial Luxury",
    description: "Translucent architecture constructs a dimensional premium stage.",
    batch: 5,
    accent: "#9defff",
    background: "#071017",
    surface: "#183443",
    foreground: "#f5fcff",
    muted: "#8da8b4",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "FORM / LIGHT / ARCHITECTURE",
    headline: "Clarity, constructed.",
    subheadline: "A precise object held inside a world of light and structure.",
    cta: "Enter the glasshouse",
  },
  {
    id: "precision-slice",
    name: "Precision Slice",
    category: "Optical",
    description: "Time-offset image slices reconstruct the product with exacting rhythm.",
    batch: 5,
    accent: "#ff3d24",
    background: "#f0ece4",
    surface: "#151515",
    foreground: "#111111",
    muted: "#6f6a62",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "ONE OBJECT / FORTY MOMENTS",
    headline: "Precision finds the whole.",
    subheadline: "Every fragment aligned into one complete expression.",
    cta: "See it resolve",
  },
  {
    id: "macro-cinema",
    name: "Macro Cinema",
    category: "Cinematography",
    description: "Extreme detail studies travel toward a complete cinematic reveal.",
    batch: 5,
    accent: "#dcb86a",
    background: "#060606",
    surface: "#1c1811",
    foreground: "#fff9ed",
    muted: "#aaa196",
    layout: "poster",
    imageFit: "contain",
    imageScale: 1,
    eyebrow: "DETAIL IS THE STORY",
    headline: "Look closer.",
    subheadline: "The complete object begins with the details others overlook.",
    cta: "See every detail",
  },
  {
    id: "gravity-field",
    name: "Gravity Field",
    category: "Experimental Tech",
    description: "Orbital forces and controlled particles stabilize around the hero.",
    batch: 5,
    accent: "#bbff2e",
    background: "#040608",
    surface: "#14211b",
    foreground: "#f4ffe7",
    muted: "#8ea192",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "FIELD TEST / STABLE",
    headline: "Find your center.",
    subheadline: "Engineered to remain composed while everything moves around it.",
    cta: "Enter the field",
  },
  {
    id: "chromatic-signal",
    name: "Chromatic Signal",
    category: "Digital Culture",
    description: "Independent color channels collide and return to perfect registration.",
    batch: 5,
    accent: "#ff3158",
    background: "#050611",
    surface: "#402dff",
    foreground: "#ffffff",
    muted: "#a7a7bd",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "SIGNAL / COLOR / LOCKED",
    headline: "Everything comes into focus.",
    subheadline: "Three channels. One unmistakable identity.",
    cta: "Lock onto the signal",
  },
  {
    id: "museum-after-dark",
    name: "Museum After Dark",
    category: "Exhibition",
    description: "Traveling architectural light discovers the product after hours.",
    batch: 5,
    accent: "#e6ba65",
    background: "#080706",
    surface: "#29231d",
    foreground: "#fff8e9",
    muted: "#a89d8e",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "PRIVATE VIEW / AFTER HOURS",
    headline: "The room belongs to one object.",
    subheadline: "A private exhibition of proportion, light, and presence.",
    cta: "Enter the exhibition",
  },
  {
    id: "paper-engineering",
    name: "Paper Engineering",
    category: "Physical Design",
    description: "Folding cardstock constructs a dimensional pop-up product stage.",
    batch: 5,
    accent: "#ff684d",
    background: "#e9dfce",
    surface: "#fff9ef",
    foreground: "#1d2c36",
    muted: "#68747a",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "CUT / FOLD / REVEAL",
    headline: "An idea takes shape.",
    subheadline: "A physical world engineered around one defining product.",
    cta: "Unfold the design",
  },
  {
    id: "lightbox-sequence",
    name: "Lightbox Sequence",
    category: "Studio Photography",
    description: "Four professional lighting setups create one complete product portrait.",
    batch: 5,
    accent: "#f3d066",
    background: "#101010",
    surface: "#e7e2da",
    foreground: "#ffffff",
    muted: "#aaa6a0",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "STUDIO TEST / FOUR LIGHTS",
    headline: "Made for the light.",
    subheadline: "Silhouette, color, texture, and form in one final exposure.",
    cta: "See the final exposure",
  },
  {
    id: "analog-campaign",
    name: "Analog Campaign",
    category: "Fashion Film",
    description: "Film strips and exposure marks build a polished archival campaign.",
    batch: 5,
    accent: "#e54832",
    background: "#d9d0bf",
    surface: "#171512",
    foreground: "#201c17",
    muted: "#70675d",
    layout: "editorial",
    imageFit: "cover",
    imageScale: 1,
    eyebrow: "CAMPAIGN ROLL / FRAME 41",
    headline: "Captured with character.",
    subheadline: "A new object with the permanence of an iconic photograph.",
    cta: "View the campaign",
  },
  {
    id: "brand-takeover",
    name: "Brand Takeover",
    category: "Global Campaign",
    description: "Environmental screens and posters build toward a full-frame launch.",
    batch: 5,
    accent: "#ff4934",
    background: "#111214",
    surface: "#ebe7de",
    foreground: "#ffffff",
    muted: "#afb0b1",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "LIVE ACROSS EVERY SCREEN",
    headline: "Own the entire frame.",
    subheadline: "From first impression to complete campaign takeover.",
    cta: "Launch everywhere",
  },
  {
    id: "motion-control",
    name: "Motion Control",
    category: "Cinematic Studio",
    description: "A precision dolly travels from macro detail to a controlled hero exposure.",
    batch: 6,
    accent: "#e2bd73",
    background: "#070707",
    surface: "#211c14",
    foreground: "#fffaf1",
    muted: "#a69f94",
    layout: "poster",
    imageFit: "contain",
    imageScale: 1,
    eyebrow: "MOTION CONTROL / SHOT 01",
    headline: "Every move has a purpose.",
    subheadline: "Precision camera movement meets a product built for scrutiny.",
    cta: "Watch the movement",
  },
  {
    id: "noir-chamber",
    name: "Noir Chamber",
    category: "Noir",
    description: "Hard light, haze, and negative space create a suspenseful product portrait.",
    batch: 6,
    accent: "#f3f0e7",
    background: "#020202",
    surface: "#181818",
    foreground: "#faf8f2",
    muted: "#9c9a95",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "LIGHT REVEALS THE TRUTH",
    headline: "Nothing hides in this light.",
    subheadline: "A defining silhouette brought forward one detail at a time.",
    cta: "Step into the light",
  },
  {
    id: "golden-hour",
    name: "Golden Hour",
    category: "Natural Cinema",
    description: "Traveling sunlight and architectural shadows create a warm cinematic reveal.",
    batch: 6,
    accent: "#e79b45",
    background: "#d8a66b",
    surface: "#f0cf9d",
    foreground: "#3b2315",
    muted: "#76533c",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "THE LIGHT BEFORE EVENING",
    headline: "Made for this moment.",
    subheadline: "Warm light, long shadows, and a product worth staying for.",
    cta: "Stay for golden hour",
  },
  {
    id: "arctic-vault",
    name: "Arctic Vault",
    category: "Cold Luxury",
    description: "Frosted architecture and suspended mist open around a pristine product.",
    batch: 6,
    accent: "#a5edff",
    background: "#07131b",
    surface: "#d9f3f7",
    foreground: "#f4fdff",
    muted: "#8fb1bd",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "TEMPERATURE / CONTROLLED",
    headline: "Clarity under pressure.",
    subheadline: "A precise object preserved inside a world of cold light.",
    cta: "Open the vault",
  },
  {
    id: "ember-forge",
    name: "Ember Forge",
    category: "Industrial Cinema",
    description: "Heat, sparks, and smoke build toward a powerful low-angle hero.",
    batch: 6,
    accent: "#ff7a24",
    background: "#090604",
    surface: "#32170b",
    foreground: "#fff3e8",
    muted: "#b89b88",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "FORGED FOR THE MOMENT",
    headline: "Built through intensity.",
    subheadline: "Heat, pressure, and purpose refined into one complete object.",
    cta: "Enter the forge",
  },
  {
    id: "neon-rain",
    name: "Neon Rain",
    category: "Night Cinema",
    description: "Neon reflections and layered rain create a premium nighttime tracking shot.",
    batch: 6,
    accent: "#ff3ca6",
    background: "#040612",
    surface: "#2837c8",
    foreground: "#f8f5ff",
    muted: "#a8a4c0",
    layout: "split",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "CITY LIGHT / AFTER MIDNIGHT",
    headline: "Own the night.",
    subheadline: "A sharp signal moving through color, reflection, and rain.",
    cta: "Follow the light",
  },
  {
    id: "tidal-light",
    name: "Tidal Light",
    category: "Fluid Cinema",
    description: "Caustic light and suspended particles create a slow underwater ascent.",
    batch: 6,
    accent: "#69f0dc",
    background: "#031b25",
    surface: "#07546a",
    foreground: "#efffff",
    muted: "#8dbcc2",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "BELOW THE SURFACE",
    headline: "Move with the light.",
    subheadline: "A quiet ascent through depth, motion, and fluid color.",
    cta: "Enter the current",
  },
  {
    id: "desert-monument",
    name: "Desert Monument",
    category: "Epic Landscape",
    description: "Atmospheric horizons and long shadows turn the product into a monument.",
    batch: 6,
    accent: "#d8793e",
    background: "#c78d5e",
    surface: "#6d3f2a",
    foreground: "#fff1dc",
    muted: "#e0c1a8",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "BUILT BEYOND THE HORIZON",
    headline: "Stand above the ordinary.",
    subheadline: "A singular object framed by distance, atmosphere, and scale.",
    cta: "Meet the monument",
  },
  {
    id: "celestial-event",
    name: "Celestial Event",
    category: "Cosmic Cinema",
    description: "An eclipse and orbital light arc reveal the product as a rare event.",
    batch: 6,
    accent: "#f4c567",
    background: "#03040a",
    surface: "#171a31",
    foreground: "#fffaf0",
    muted: "#989bad",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "A RARE ALIGNMENT",
    headline: "The moment everything aligns.",
    subheadline: "Light, motion, and form converge around one extraordinary object.",
    cta: "Witness the event",
  },
  {
    id: "directors-cut",
    name: "Director's Cut",
    category: "Prestige Film",
    description: "Cinematic framing and deliberate inserts build a definitive campaign film.",
    batch: 6,
    accent: "#d83e2f",
    background: "#080808",
    surface: "#e5ded2",
    foreground: "#fffaf2",
    muted: "#aaa39a",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 1,
    eyebrow: "DIRECTOR'S CUT / FINAL PRINT",
    headline: "This is the defining shot.",
    subheadline: "Every frame considered. Every detail moving toward one final image.",
    cta: "Watch the final cut",
  },
  {
    id: "luxury-object",
    name: "Luxury Object",
    category: "Luxury",
    description: "Sculpted light and deep negative space for fragrance, jewelry, and premium accessories.",
    batch: 7,
    accent: "#c9a35d",
    background: "#050505",
    surface: "#17130e",
    foreground: "#fffaf0",
    muted: "#aaa295",
    layout: "poster",
    imageFit: "contain",
    imageScale: 1,
    eyebrow: "EDITION / 001",
    headline: "Presence needs no introduction.",
    subheadline: "An object defined by proportion, material, and restraint.",
    cta: "Discover the edition",
  },
  {
    id: "beauty-ritual",
    name: "Beauty Ritual",
    category: "Beauty",
    description: "Luminous daylight and translucent color for skincare, cosmetics, and wellness.",
    batch: 7,
    accent: "#d65d86",
    background: "#f4ddd9",
    surface: "#fff7f3",
    foreground: "#3b202a",
    muted: "#8d6874",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "THE DAILY RITUAL",
    headline: "Begin with radiance.",
    subheadline: "A considered essential for the moments you keep for yourself.",
    cta: "Meet your ritual",
  },
  {
    id: "performance-engine",
    name: "Performance Engine",
    category: "Performance",
    description: "Compressed anticipation and decisive acceleration for sport, tools, and equipment.",
    batch: 7,
    accent: "#d7ff23",
    background: "#080b09",
    surface: "#182018",
    foreground: "#f7faef",
    muted: "#a0aa9c",
    layout: "technical",
    imageFit: "contain",
    imageScale: 1,
    eyebrow: "ENGINEERED / FULL OUTPUT",
    headline: "Performance without hesitation.",
    subheadline: "Built to respond the instant the moment demands it.",
    cta: "Activate performance",
  },
  {
    id: "technology-keynote",
    name: "Technology Keynote",
    category: "Technology",
    description: "An architectural launch stage for devices and category-defining technology.",
    batch: 7,
    accent: "#6c8cff",
    background: "#070910",
    surface: "#151a2a",
    foreground: "#f7f8ff",
    muted: "#9da5bd",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "INTRODUCING THE NEXT",
    headline: "A new standard takes the stage.",
    subheadline: "Designed to make advanced technology feel inevitable.",
    cta: "Explore what’s next",
  },
  {
    id: "tabletop-appetite",
    name: "Tabletop Appetite",
    category: "Food & Beverage",
    description: "Warm tactile surfaces and satisfying packshot motion for food, drink, and supplements.",
    batch: 7,
    accent: "#d9502a",
    background: "#edc788",
    surface: "#f6e5c4",
    foreground: "#3a2014",
    muted: "#7d5a45",
    layout: "split",
    imageFit: "contain",
    imageScale: 1,
    eyebrow: "MADE FOR EVERY DAY",
    headline: "The good part starts here.",
    subheadline: "A daily favorite, presented with warmth and unmistakable appetite.",
    cta: "Bring it home",
  },
  {
    id: "fashion-campaign",
    name: "Fashion Campaign",
    category: "Fashion",
    description: "Confident editorial crops and asymmetric typography for apparel and accessories.",
    batch: 7,
    accent: "#e83d24",
    background: "#ded7ca",
    surface: "#f5f1e9",
    foreground: "#171410",
    muted: "#6e665c",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 1,
    eyebrow: "THE SEASON / ISSUE 07",
    headline: "Wear the point of view.",
    subheadline: "A campaign for products with a silhouette of their own.",
    cta: "Shop the campaign",
  },
  {
    id: "home-editorial",
    name: "Home Editorial",
    category: "Home",
    description: "Designed interior light and calm spatial movement for home and lifestyle products.",
    batch: 7,
    accent: "#97704c",
    background: "#ddd5c8",
    surface: "#f0ebe3",
    foreground: "#2d2923",
    muted: "#766e64",
    layout: "split",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "OBJECTS FOR LIVING",
    headline: "Make space for better.",
    subheadline: "Thoughtful form, natural light, and an effortless place at home.",
    cta: "See it in your space",
  },
  {
    id: "outdoor-proven",
    name: "Outdoor Proven",
    category: "Outdoor",
    description: "Grounded scale and atmospheric depth for travel, rugged, and outdoor products.",
    batch: 7,
    accent: "#ef9f43",
    background: "#1b2421",
    surface: "#4c5d4d",
    foreground: "#fff5df",
    muted: "#b7c0ad",
    layout: "poster",
    imageFit: "contain",
    imageScale: 1,
    eyebrow: "FIELD TEST / READY",
    headline: "Ready beyond the pavement.",
    subheadline: "Dependable design for wherever the route stops being predictable.",
    cta: "Take it outside",
  },
  {
    id: "retail-impact",
    name: "Retail Impact",
    category: "Retail",
    description: "Immediate product recognition and disciplined color blocking for ecommerce and CPG.",
    batch: 7,
    accent: "#ff442f",
    background: "#ffe43b",
    surface: "#ffffff",
    foreground: "#101114",
    muted: "#615d3e",
    layout: "poster",
    imageFit: "contain",
    imageScale: 1,
    eyebrow: "NEW / AVAILABLE NOW",
    headline: "The one they notice first.",
    subheadline: "Maximum recognition, unmistakable value, and a clear reason to choose.",
    cta: "Shop it now",
  },
  {
    id: "future-essential",
    name: "Future Essential",
    category: "Innovation",
    description: "Restrained unfamiliar space and iconic light for innovative products.",
    batch: 7,
    accent: "#b6a2ff",
    background: "#090816",
    surface: "#24203e",
    foreground: "#f9f6ff",
    muted: "#aaa3bf",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "THE CATEGORY CHANGES HERE",
    headline: "Tomorrow becomes essential.",
    subheadline: "A new object for a future that already feels within reach.",
    cta: "Meet what’s next",
  },
  {
    id: "angle-study",
    name: "Angle Study",
    category: "Multi-Angle",
    description: "Three real product viewpoints match-cut into one definitive hero portrait.",
    batch: 8,
    accent: "#f15a3d",
    background: "#e9e4da",
    surface: "#171717",
    foreground: "#151515",
    muted: "#6f695f",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.96,
    eyebrow: "THREE ANGLES / ONE OBJECT",
    headline: "Every side earns attention.",
    subheadline: "Front, profile, and form resolve into one unmistakable product.",
    cta: "See every angle",
    mediaSlots: [
      {id: "hero", label: "Front angle", kind: "image", removeBackground: true},
      {id: "angleSide", label: "Side angle", kind: "image", removeBackground: true},
      {id: "angleThreeQuarter", label: "Three-quarter angle", kind: "image", removeBackground: true},
    ],
  },
  {
    id: "detail-proof",
    name: "Detail Proof",
    category: "Craft",
    description: "Real detail photography establishes craftsmanship before the complete product reveal.",
    batch: 8,
    accent: "#d3ad62",
    background: "#080808",
    surface: "#1a1815",
    foreground: "#fff9ed",
    muted: "#aaa196",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.96,
    eyebrow: "CRAFT / DETAIL / COMPLETE",
    headline: "The difference is in the details.",
    subheadline: "Every surface, finish, and decision leads to the complete object.",
    cta: "Look closer",
    mediaSlots: [
      {id: "hero", label: "Hero product", kind: "image", removeBackground: true},
      {id: "detailOne", label: "Detail image 1", kind: "image"},
      {id: "detailTwo", label: "Detail image 2", kind: "image"},
    ],
  },
  {
    id: "product-in-context",
    name: "Product in Context",
    category: "Lifestyle",
    description: "A clean product introduction opens into a real lifestyle environment.",
    batch: 8,
    accent: "#ff6b4a",
    background: "#ece3d6",
    surface: "#fcf7ef",
    foreground: "#1b1713",
    muted: "#70675d",
    layout: "split",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "OBJECT / PLACE / PURPOSE",
    headline: "Designed for real life.",
    subheadline: "A clear product promise, grounded in the place it belongs.",
    cta: "See it in context",
    mediaSlots: [
      {id: "hero", label: "Product image", kind: "image", removeBackground: true},
      {id: "lifestyleImage", label: "Lifestyle image", kind: "image"},
    ],
  },
  {
    id: "live-demonstration",
    name: "Live Demonstration",
    category: "Product Demo",
    description: "A genuine demonstration clip proves how the product behaves before the final packshot.",
    batch: 8,
    accent: "#95ff45",
    background: "#080b09",
    surface: "#142017",
    foreground: "#f3ffed",
    muted: "#9cad96",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "SEE IT WORK",
    headline: "Performance, demonstrated.",
    subheadline: "Real motion makes the product promise visible.",
    cta: "Watch it work",
    mediaSlots: [
      {id: "hero", label: "Product image", kind: "image", removeBackground: true},
      {id: "demoVideo", label: "Demonstration video", kind: "video"},
    ],
  },
  {
    id: "before-after",
    name: "Before / After",
    category: "Transformation",
    description: "Real before-and-after evidence creates an immediate transformation story.",
    batch: 8,
    accent: "#4169ff",
    background: "#f0eee8",
    surface: "#ffffff",
    foreground: "#111318",
    muted: "#686b73",
    layout: "split",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "BEFORE / AFTER / PROVEN",
    headline: "See the change.",
    subheadline: "A direct comparison makes the product result impossible to miss.",
    cta: "See the result",
    mediaSlots: [
      {id: "hero", label: "Product image", kind: "image", removeBackground: true},
      {id: "beforeImage", label: "Before image", kind: "image"},
      {id: "afterImage", label: "After image", kind: "image"},
    ],
  },
  {
    id: "colorway-collection",
    name: "Colorway Collection",
    category: "Collection",
    description: "Three real product variants move through one controlled campaign system.",
    batch: 8,
    accent: "#ff4d75",
    background: "#f6f1e8",
    surface: "#222031",
    foreground: "#17141d",
    muted: "#746d7c",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "THE COLLECTION / THREE WAYS",
    headline: "Choose your expression.",
    subheadline: "One design language, presented in three distinct product finishes.",
    cta: "Explore the collection",
    mediaSlots: [
      {id: "hero", label: "Variant 1", kind: "image", removeBackground: true},
      {id: "variantTwo", label: "Variant 2", kind: "image", removeBackground: true},
      {id: "variantThree", label: "Variant 3", kind: "image", removeBackground: true},
    ],
  },
  {
    id: "package-to-product",
    name: "Package to Product",
    category: "Unboxing",
    description: "Real packaged and unpacked states create an honest premium reveal.",
    batch: 8,
    accent: "#e63f2f",
    background: "#ded7ca",
    surface: "#f8f3e9",
    foreground: "#17130f",
    muted: "#70675c",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.95,
    eyebrow: "ARRIVAL / OPEN / REVEAL",
    headline: "The experience starts before it opens.",
    subheadline: "Packaging and product become one complete arrival.",
    cta: "Open the experience",
    mediaSlots: [
      {id: "packageImage", label: "Packaged product", kind: "image", removeBackground: true},
      {id: "unpackedImage", label: "Unpacked product", kind: "image", removeBackground: true},
    ],
  },
  {
    id: "feature-in-focus",
    name: "Feature in Focus",
    category: "Feature Story",
    description: "Real feature imagery connects specific evidence to the complete product.",
    batch: 8,
    accent: "#36d8ff",
    background: "#060a10",
    surface: "#13202c",
    foreground: "#f2fbff",
    muted: "#93a9b7",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "FEATURE / EVIDENCE / HERO",
    headline: "Built around what matters.",
    subheadline: "Two defining capabilities lead back to one complete product.",
    cta: "Explore the features",
    mediaSlots: [
      {id: "hero", label: "Product image", kind: "image", removeBackground: true},
      {id: "featureOne", label: "Feature image 1", kind: "image"},
      {id: "featureTwo", label: "Feature image 2", kind: "image"},
    ],
  },
  {
    id: "human-moment",
    name: "Human Moment",
    category: "Lifestyle Film",
    description: "Real lifestyle footage establishes emotion before a refined product finish.",
    batch: 8,
    accent: "#ffd86a",
    background: "#17120d",
    surface: "#3d3024",
    foreground: "#fff8eb",
    muted: "#c1ac91",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "MADE FOR THE MOMENT",
    headline: "The product becomes part of the story.",
    subheadline: "Human context turns a useful object into a meaningful one.",
    cta: "Enter the moment",
    mediaSlots: [
      {id: "hero", label: "Product image", kind: "image", removeBackground: true},
      {id: "lifestyleVideo", label: "Lifestyle video", kind: "video"},
    ],
  },
  {
    id: "campaign-cut",
    name: "Campaign Cut",
    category: "Campaign Film",
    description: "Hero, lifestyle, and motion assets combine into one complete campaign edit.",
    batch: 8,
    accent: "#ff4438",
    background: "#111111",
    surface: "#f0eadf",
    foreground: "#ffffff",
    muted: "#b5afa7",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.96,
    eyebrow: "MASTER CAMPAIGN / LIVE",
    headline: "One product. A complete campaign.",
    subheadline: "Product clarity, real context, and motion resolve into one final asset.",
    cta: "Launch the campaign",
    mediaSlots: [
      {id: "hero", label: "Hero product", kind: "image", removeBackground: true},
      {id: "campaignImage", label: "Campaign image", kind: "image"},
      {id: "campaignVideo", label: "Campaign video", kind: "video"},
    ],
  },
  {
    id: "curtain-call",
    name: "Curtain Call",
    category: "Theatrical",
    description: "A restrained theatrical conceal-and-reveal built around one decisive hero moment.",
    batch: 9,
    accent: "#f2c96d",
    background: "#090909",
    surface: "#24190f",
    foreground: "#fff8e8",
    muted: "#b4a48b",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "PRESENTING",
    headline: "Worth the wait.",
    subheadline: "Anticipation gives way to one unforgettable product.",
    cta: "Take the stage",
  },
  {
    id: "stage-flats",
    name: "Stage Flats",
    category: "Set Design",
    description: "Graphic scenery unfolds around one product from a deliberately fixed camera.",
    batch: 9,
    accent: "#ff684f",
    background: "#e8dfd0",
    surface: "#173f48",
    foreground: "#111312",
    muted: "#665f55",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "ONE OBJECT / THREE ACTS",
    headline: "The world moves around it.",
    subheadline: "A graphic stage built to make the product impossible to miss.",
    cta: "Enter the scene",
  },
  {
    id: "frame-step",
    name: "Frame Step",
    category: "Tactile Motion",
    description: "Deliberately stepped timing gives one product a crafted stop-motion character.",
    batch: 9,
    accent: "#ff4f7d",
    background: "#f4e9d8",
    surface: "#2a68ff",
    foreground: "#161616",
    muted: "#70685e",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "POSE / HOLD / MOVE",
    headline: "Made to move differently.",
    subheadline: "Tactile rhythm turns every pose into a statement.",
    cta: "See the difference",
  },
  {
    id: "projection-room",
    name: "Projection Room",
    category: "Cinema",
    description: "Responsive projector beams and apertures turn the product reveal into an event.",
    batch: 9,
    accent: "#62dfff",
    background: "#05080d",
    surface: "#101b28",
    foreground: "#f5fbff",
    muted: "#8da5b6",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.96,
    eyebrow: "NOW SHOWING",
    headline: "Made for the big screen.",
    subheadline: "Light, atmosphere, and one product in perfect focus.",
    cta: "Watch the premiere",
  },
  {
    id: "silhouette-trace",
    name: "Silhouette Trace",
    category: "Form",
    description: "Edge light establishes the product shape before color and detail arrive.",
    batch: 9,
    accent: "#c6ff4d",
    background: "#030504",
    surface: "#112019",
    foreground: "#f6fff0",
    muted: "#8fa18d",
    layout: "split",
    imageFit: "contain",
    imageScale: 0.96,
    eyebrow: "FORM / RECOGNIZED",
    headline: "Iconic before it is revealed.",
    subheadline: "A silhouette strong enough to speak before the details do.",
    cta: "Meet the icon",
  },
  {
    id: "object-choreography",
    name: "Object Choreography",
    category: "Motion Direction",
    description: "A precise compress-separate-align-lock movement resolves into one hero product.",
    batch: 9,
    accent: "#ff5d35",
    background: "#eee8dc",
    surface: "#1c2850",
    foreground: "#111319",
    muted: "#68645d",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.88,
    eyebrow: "MOTION / WITH PURPOSE",
    headline: "Every move has a reason.",
    subheadline: "Controlled choreography turns function into visual identity.",
    cta: "See it align",
  },
  {
    id: "five-beat-film",
    name: "Five-Beat Film",
    category: "Modular Campaign",
    description: "Five self-contained visual beats combine into one disciplined commercial.",
    batch: 9,
    accent: "#ffd500",
    background: "#111111",
    surface: "#2644ff",
    foreground: "#ffffff",
    muted: "#b6b6b6",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "FIVE BEATS / ONE MESSAGE",
    headline: "Built to land every point.",
    subheadline: "Identity, tension, reveal, proof, and one final packshot.",
    cta: "Make it count",
  },
  {
    id: "worlds-around-object",
    name: "Worlds Around One Object",
    category: "Graphic Journey",
    description: "Three graphic environments travel past one consistent, truthful product image.",
    batch: 9,
    accent: "#ff563e",
    background: "#e7f1ec",
    surface: "#173d35",
    foreground: "#12201d",
    muted: "#64736d",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.93,
    eyebrow: "ONE OBJECT / MANY WORLDS",
    headline: "At home everywhere.",
    subheadline: "The scenery changes. The product remains unmistakable.",
    cta: "Travel further",
  },
  {
    id: "living-still",
    name: "Living Still",
    category: "Cinemagraph",
    description: "A composed hero image comes alive through only light, shadow, and restrained type.",
    batch: 9,
    accent: "#d6ff68",
    background: "#16170f",
    surface: "#303326",
    foreground: "#fbfbea",
    muted: "#a9aa94",
    layout: "split",
    imageFit: "contain",
    imageScale: 0.95,
    eyebrow: "STILL / NOT STATIC",
    headline: "Quietly impossible to ignore.",
    subheadline: "The smallest movement can hold the longest attention.",
    cta: "Stay with it",
  },
  {
    id: "tension-release",
    name: "Tension / Release",
    category: "Hero Commercial",
    description: "Progressive visual pressure releases into a spacious, authoritative final packshot.",
    batch: 9,
    accent: "#ff3f34",
    background: "#f0ede5",
    surface: "#111111",
    foreground: "#111111",
    muted: "#6c6860",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.95,
    eyebrow: "ANTICIPATION / ARRIVAL",
    headline: "The moment everything opens.",
    subheadline: "Pressure builds. The product delivers the release.",
    cta: "Experience the arrival",
  },
  {
    id: "reverse-reveal",
    name: "Reverse Reveal",
    category: "Reverse Edit",
    description: "A finished packshot appears first, deconstructs backward, then returns with authority.",
    batch: 10,
    accent: "#f04f3d",
    background: "#efe9de",
    surface: "#111111",
    foreground: "#141414",
    muted: "#6e685f",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "END / BEGIN / END",
    headline: "The finish was only the beginning.",
    subheadline: "A complete product story, revealed in reverse.",
    cta: "Watch it return",
  },
  {
    id: "false-ending",
    name: "False Ending",
    category: "Narrative Twist",
    description: "An early end card gives way to a second, stronger product payoff.",
    batch: 10,
    accent: "#f6d54a",
    background: "#090909",
    surface: "#262626",
    foreground: "#ffffff",
    muted: "#aaa9a4",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "WAIT / THERE IS MORE",
    headline: "You thought it was over.",
    subheadline: "The second reveal is the one that stays with you.",
    cta: "See the real ending",
  },
  {
    id: "dual-timeline",
    name: "Dual Timeline",
    category: "Split Narrative",
    description: "Restrained and energetic versions of one product story converge into one frame.",
    batch: 10,
    accent: "#ff5d35",
    background: "#eee8dd",
    surface: "#172b52",
    foreground: "#121419",
    muted: "#6c675e",
    layout: "split",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "CALM / ENERGY / ONE",
    headline: "Two stories. One conclusion.",
    subheadline: "Different rhythms meet at the same unmistakable product.",
    cta: "See them converge",
  },
  {
    id: "flashbulb-editorial",
    name: "Flashbulb Editorial",
    category: "Fashion Photography",
    description: "Controlled flashes create a sequence of deliberate campaign photographs.",
    batch: 10,
    accent: "#ff496f",
    background: "#d9d3c8",
    surface: "#111111",
    foreground: "#111111",
    muted: "#68625b",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.96,
    eyebrow: "CAMPAIGN / FRAME 04",
    headline: "Every frame is the hero frame.",
    subheadline: "A photographic sequence built around presence and precision.",
    cta: "Enter the campaign",
  },
  {
    id: "invisible-cut",
    name: "Invisible Cut",
    category: "Continuous Camera",
    description: "Foreground wipes hide radical composition changes inside one continuous illusion.",
    batch: 10,
    accent: "#78e9ca",
    background: "#0c1818",
    surface: "#1d3837",
    foreground: "#f1fff9",
    muted: "#95aea7",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.95,
    eyebrow: "ONE MOVE / THREE SCENES",
    headline: "The cut you never see.",
    subheadline: "One uninterrupted motion carries the product through every scene.",
    cta: "Follow the motion",
  },
  {
    id: "speed-ramp",
    name: "Speed Ramp",
    category: "Timing Contrast",
    description: "Long precision holds collide with split-second product repositioning.",
    batch: 10,
    accent: "#ff4b25",
    background: "#f1eadc",
    surface: "#1928ae",
    foreground: "#111111",
    muted: "#6d665c",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "HOLD / MOVE / HOLD",
    headline: "Stillness makes speed matter.",
    subheadline: "Precision timing turns a single movement into an event.",
    cta: "Feel the shift",
  },
  {
    id: "call-response",
    name: "Call / Response",
    category: "Copy Dialogue",
    description: "Three written claims receive three visual answers from the product.",
    batch: 10,
    accent: "#d8ff45",
    background: "#10120c",
    surface: "#2d3122",
    foreground: "#fbffe9",
    muted: "#a9ad95",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "ASK / ANSWER",
    headline: "The product answers.",
    subheadline: "Every statement resolves into visible product confidence.",
    cta: "Ask for more",
  },
  {
    id: "the-interruption",
    name: "The Interruption",
    category: "Disruptive Campaign",
    description: "A polished conventional ad is interrupted by a graphic event the product controls.",
    batch: 10,
    accent: "#ffef38",
    background: "#f0ede5",
    surface: "#ff3d35",
    foreground: "#101010",
    muted: "#68635b",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "WE INTERRUPT THIS AD",
    headline: "Some products refuse the background.",
    subheadline: "A sudden break becomes the strongest product statement.",
    cta: "Take over the frame",
  },
  {
    id: "palindrome",
    name: "Palindrome",
    category: "Seamless Loop",
    description: "A symmetrical five-second movement reverses perfectly into its opening frame.",
    batch: 10,
    accent: "#a996ff",
    background: "#0f0b19",
    surface: "#28203d",
    foreground: "#faf7ff",
    muted: "#aaa0bd",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "FORWARD / REVERSE",
    headline: "Made to be watched again.",
    subheadline: "A complete cinematic loop with no visible beginning or end.",
    cta: "Stay in the loop",
  },
  {
    id: "the-callback",
    name: "The Callback",
    category: "Setup & Payoff",
    description: "A simple opening motif develops through the film and resolves around the product.",
    batch: 10,
    accent: "#ff6348",
    background: "#e9e2d5",
    surface: "#183b43",
    foreground: "#121817",
    muted: "#68716d",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "REMEMBER THIS",
    headline: "Every detail comes back.",
    subheadline: "The opening clue becomes the final product signature.",
    cta: "See the connection",
  },
  {
    id: "frame-magnet",
    name: "Frame Magnet",
    category: "Continuous Composition",
    description: "The product travels through four connected compositions while every element responds to its position.",
    batch: 11,
    accent: "#ff5f45",
    background: "#eee9df",
    surface: "#172737",
    foreground: "#14171a",
    muted: "#6d6961",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "FOLLOW THE OBJECT",
    headline: "Attention moves with it.",
    subheadline: "One uninterrupted path turns every position into a deliberate product frame.",
    cta: "Follow the movement",
  },
  {
    id: "negative-space",
    name: "Negative Space",
    category: "Minimal Suspense",
    description: "An intentionally empty composition builds anticipation until the product occupies the only correct position.",
    batch: 11,
    accent: "#d6ff4b",
    background: "#10120d",
    surface: "#25291d",
    foreground: "#f7faed",
    muted: "#a3aa91",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "SPACE / RESERVED",
    headline: "This frame was waiting.",
    subheadline: "Absence creates the tension. Arrival makes the product inevitable.",
    cta: "Take your place",
  },
  {
    id: "scale-relay",
    name: "Scale Relay",
    category: "Editorial Scale",
    description: "Macro, hero, and miniature product views pass one continuous movement between scales.",
    batch: 11,
    accent: "#ffcf4a",
    background: "#f0eadf",
    surface: "#20201f",
    foreground: "#151515",
    muted: "#6e6860",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.95,
    eyebrow: "DETAIL / FORM / PRESENCE",
    headline: "Every scale tells the story.",
    subheadline: "The closest detail and the complete object belong to the same continuous idea.",
    cta: "See the whole",
  },
  {
    id: "blindside",
    name: "Blindside",
    category: "Foreground Reveal",
    description: "Oversized product crops pass close to camera and reveal progressively cleaner hero compositions.",
    batch: 11,
    accent: "#6de7ff",
    background: "#07151c",
    surface: "#153543",
    foreground: "#f2fbff",
    muted: "#91aab4",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "CLOSER THAN EXPECTED",
    headline: "The reveal was in front of you.",
    subheadline: "Foreground movement turns the product itself into the transition.",
    cta: "See what clears",
  },
  {
    id: "counterweight",
    name: "Counterweight",
    category: "Balanced Motion",
    description: "Product and message move in opposition, then settle into a precisely balanced campaign frame.",
    batch: 11,
    accent: "#ff6b36",
    background: "#e8e2d7",
    surface: "#1b3340",
    foreground: "#17191a",
    muted: "#69675f",
    layout: "split",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "WEIGHT / BALANCE",
    headline: "Every move finds its balance.",
    subheadline: "Product and message carry equal visual weight without competing for attention.",
    cta: "Find the balance",
  },
  {
    id: "echo-exit",
    name: "Echo Exit",
    category: "Motion Residue",
    description: "Product echoes preserve the path of movement before peeling away to reveal one definitive hero.",
    batch: 11,
    accent: "#ff4b86",
    background: "#160c15",
    surface: "#382035",
    foreground: "#fff4fb",
    muted: "#b69aaa",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "MOTION LEAVES A TRACE",
    headline: "Only one image remains.",
    subheadline: "Every echo records the journey. The final product owns the destination.",
    cta: "Stay with the original",
  },
  {
    id: "wordmark-passage",
    name: "Wordmark Passage",
    category: "Type & Depth",
    description: "Campaign typography travels behind, through, and in front of the product to create cinematic depth.",
    batch: 11,
    accent: "#fbff52",
    background: "#121212",
    surface: "#2a2a2a",
    foreground: "#ffffff",
    muted: "#aaaaa5",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "OBJECT / MESSAGE",
    headline: "The message moves through it.",
    subheadline: "Type and product share one depth-driven campaign composition.",
    cta: "Read the object",
  },
  {
    id: "still-point",
    name: "Still Point",
    category: "Controlled Motion",
    description: "The product remains perfectly still while crops, copy, and framing move around its fixed position.",
    batch: 11,
    accent: "#86f0d0",
    background: "#0b1615",
    surface: "#203431",
    foreground: "#f1fffb",
    muted: "#93aaa4",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "THE FRAME MOVES",
    headline: "The center never has to.",
    subheadline: "Complete composure becomes the strongest movement in the film.",
    cta: "Hold your ground",
  },
  {
    id: "contour-cut",
    name: "Contour Cut",
    category: "Match Editing",
    description: "Successive product crops align on a shared contour so every hard cut preserves visual momentum.",
    batch: 11,
    accent: "#ff744d",
    background: "#eee7dc",
    surface: "#242b46",
    foreground: "#15171c",
    muted: "#6b675f",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.96,
    eyebrow: "CUT ON FORM",
    headline: "Every edge leads forward.",
    subheadline: "Product geometry becomes the edit without adding decorative geometry.",
    cta: "Follow the contour",
  },
  {
    id: "last-one-standing",
    name: "Last One Standing",
    category: "Reduction Edit",
    description: "A crowded product composition simplifies through decisive cuts until one hero remains.",
    batch: 11,
    accent: "#ffd447",
    background: "#17140c",
    surface: "#39321c",
    foreground: "#fff9e8",
    muted: "#b0a58a",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "REMOVE THE COMPETITION",
    headline: "One product owns the frame.",
    subheadline: "Each cut removes distraction until nothing remains but the strongest choice.",
    cta: "Choose the one",
  },
  {
    id: "material-noir",
    name: "Material Noir",
    category: "Tactile Luxury",
    description: "A grazing beam discovers the material before the product emerges from shadow.",
    batch: 12,
    accent: "#e0b86a",
    background: "#080706",
    surface: "#211b14",
    foreground: "#fff8ea",
    muted: "#b4a58d",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.96,
    eyebrow: "MATERIAL / AFTER DARK",
    headline: "Texture becomes atmosphere.",
    subheadline: "A tactile surface, a controlled beam, and one product in complete focus.",
    cta: "Enter the material",
    polyHavenDefaultAssetId: "marble_01",
  },
  {
    id: "mineral-gallery",
    name: "Mineral Gallery",
    category: "Architectural",
    description: "Monumental material panels open into a calm museum-scale product portrait.",
    batch: 12,
    accent: "#d7c6aa",
    background: "#d8d1c5",
    surface: "#f2ede4",
    foreground: "#201d19",
    muted: "#6f685e",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "OBJECT / MATERIAL / SPACE",
    headline: "A gallery built around one object.",
    subheadline: "Natural surface and architectural scale give the product a permanent presence.",
    cta: "Enter the gallery",
    polyHavenDefaultAssetId: "grey_cartago_03",
  },
  {
    id: "wet-asphalt",
    name: "Wet Asphalt",
    category: "Night Performance",
    description: "A low tracking move across a reflective surface resolves into an illuminated hero.",
    batch: 12,
    accent: "#66d8ff",
    background: "#05090c",
    surface: "#13232d",
    foreground: "#f2fbff",
    muted: "#8da7b3",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.98,
    eyebrow: "AFTER HOURS / FULL OUTPUT",
    headline: "Performance leaves a reflection.",
    subheadline: "Night light, grounded texture, and decisive movement frame the product at speed.",
    cta: "Own the night",
    polyHavenDefaultAssetId: "asphalt_02",
  },
  {
    id: "travertine-sun",
    name: "Travertine Sun",
    category: "Warm Luxury",
    description: "Long daylight moves across stone before revealing a warm editorial packshot.",
    batch: 12,
    accent: "#a9562d",
    background: "#d6b78e",
    surface: "#f3dfc1",
    foreground: "#332116",
    muted: "#795f4c",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "LIGHT / STONE / FORM",
    headline: "Made for the warmest hour.",
    subheadline: "Natural material and directional light turn a simple product shot into a destination.",
    cta: "Follow the light",
    polyHavenDefaultAssetId: "sandstone_cracks",
  },
  {
    id: "brushed-alloy",
    name: "Brushed Alloy",
    category: "Industrial Precision",
    description: "A scanning highlight and machined surface create a precise technical reveal.",
    batch: 12,
    accent: "#ff623f",
    background: "#111419",
    surface: "#343a42",
    foreground: "#f5f7fa",
    muted: "#a0a8b2",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "PRECISION / MATERIAL TEST",
    headline: "Engineered down to the surface.",
    subheadline: "Controlled highlights and measured movement make every finish feel intentional.",
    cta: "Inspect the build",
    polyHavenDefaultAssetId: "blue_metal_plate",
  },
  {
    id: "paper-atelier",
    name: "Paper Atelier",
    category: "Editorial Craft",
    description: "Torn editorial windows and tactile paper create an authored campaign sequence.",
    batch: 12,
    accent: "#d43c2c",
    background: "#e8e0d2",
    surface: "#fffaf1",
    foreground: "#171512",
    muted: "#6c655c",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "THE MATERIAL EDIT",
    headline: "Craft becomes the campaign.",
    subheadline: "Paper, image, and typography assemble into one tactile product story.",
    cta: "Open the edition",
    polyHavenDefaultAssetId: "painted_plaster_wall",
  },
  {
    id: "concrete-runway",
    name: "Concrete Runway",
    category: "Urban Fashion",
    description: "A hard architectural runway carries the product through an urban campaign reveal.",
    batch: 12,
    accent: "#e4ff36",
    background: "#151615",
    surface: "#4a4b47",
    foreground: "#f7f7f0",
    muted: "#aaa99e",
    layout: "split",
    imageFit: "contain",
    imageScale: 1,
    eyebrow: "CITY / OBJECT / MOTION",
    headline: "Built for the hard light.",
    subheadline: "Urban texture and runway pacing give the product a confident point of view.",
    cta: "Take the runway",
    polyHavenDefaultAssetId: "concrete_floor_worn_001",
  },
  {
    id: "velvet-chamber",
    name: "Velvet Chamber",
    category: "Prestige Beauty",
    description: "Soft folds and a slow spotlight create a theatrical luxury unveiling.",
    batch: 12,
    accent: "#f0be8e",
    background: "#16080f",
    surface: "#48172d",
    foreground: "#fff5f2",
    muted: "#c29aa8",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "PRIVATE VIEW / TONIGHT",
    headline: "The room opens for one object.",
    subheadline: "Soft material, deep color, and deliberate light create a private unveiling.",
    cta: "Enter the chamber",
    polyHavenDefaultAssetId: "velour_velvet",
  },
  {
    id: "timber-ritual",
    name: "Timber Ritual",
    category: "Natural Lifestyle",
    description: "Morning light and organic surface movement build a grounded daily ritual.",
    batch: 12,
    accent: "#d26f3f",
    background: "#b98c63",
    surface: "#ead5b9",
    foreground: "#2d1c12",
    muted: "#70533e",
    layout: "split",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "MORNING / MADE BETTER",
    headline: "A ritual with natural character.",
    subheadline: "Warm material and measured daylight make an everyday object feel considered.",
    cta: "Begin the ritual",
    polyHavenDefaultAssetId: "oak_veneer_01",
  },
  {
    id: "studio-archive",
    name: "Studio Archive",
    category: "Material Montage",
    description: "Contact sheets, material crops, and a final clean hero form a complete campaign study.",
    batch: 12,
    accent: "#ffca3a",
    background: "#101113",
    surface: "#efeadf",
    foreground: "#171717",
    muted: "#69655e",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "ARCHIVE / MATERIAL STUDY",
    headline: "Every surface leaves evidence.",
    subheadline: "A cinematic material study resolves into one definitive campaign image.",
    cta: "View the archive",
    polyHavenDefaultAssetId: "terrazzo_tiles",
  },
];

export const getProductTemplate = (id: ProductTemplateId) => {
  const template = productTemplates.find((item) => item.id === id);
  if (!template) throw new Error(`Unknown product template: ${id}`);
  return template;
};

export const productVideoDuration = 180;
export const productVideoBatch2Duration = 240;
export const productVideoBatch3Duration = 240;
export const productVideoBatch4Duration = 240;
export const productVideoBatch5Duration = 300;
export const productVideoBatch6Duration = 300;
export const productVideoBatch7Duration = 300;
export const productVideoBatch8Duration = 300;
export const productVideoBatch9Duration = 300;
export const productVideoBatch10Duration = 300;
export const productVideoBatch11Duration = 300;
export const productVideoBatch12Duration = 300;

export const getProductVideoDuration = (templateId: ProductTemplateId) => {
  const batch = getProductTemplate(templateId).batch;
  if (batch === 2) return productVideoBatch2Duration;
  if (batch === 3) return productVideoBatch3Duration;
  if (batch === 4) return productVideoBatch4Duration;
  if (batch === 5) return productVideoBatch5Duration;
  if (batch === 6) return productVideoBatch6Duration;
  if (batch === 7) return productVideoBatch7Duration;
  if (batch === 8) return productVideoBatch8Duration;
  if (batch === 9) return productVideoBatch9Duration;
  if (batch === 10) return productVideoBatch10Duration;
  if (batch === 11) return productVideoBatch11Duration;
  if (batch === 12) return productVideoBatch12Duration;
  return productVideoDuration;
};
