export type ProductTemplateId =
  | "obsidian"
  | "gallery"
  | "kinetic"
  | "aura"
  | "editorial"
  | "precision"
  | "monument"
  | "chromatic"
  | "launch"
  | "essential"
  | "eclipse"
  | "swiss"
  | "type-impact"
  | "triptych"
  | "liquid"
  | "blueprint"
  | "pop-tile"
  | "pedestal"
  | "countdown"
  | "scrapbook";

export type ProductTemplate = {
  id: ProductTemplateId;
  name: string;
  category: string;
  description: string;
  batch: 1 | 2;
  accent: string;
  background: string;
  surface: string;
  foreground: string;
  muted: string;
  layout:
    | "split"
    | "center"
    | "poster"
    | "editorial"
    | "technical";
  imageFit: "contain" | "cover";
  imageScale: number;
  eyebrow: string;
  headline: string;
  subheadline: string;
  cta: string;
};

export const productTemplates: ProductTemplate[] = [
  {
    id: "obsidian",
    name: "Obsidian Reveal",
    category: "Luxury",
    description: "Dark cinematic launch with a focused product reveal.",
    batch: 1,
    accent: "#d8ad55",
    background: "#090909",
    surface: "#141414",
    foreground: "#f7f3ea",
    muted: "#aaa49a",
    layout: "split",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "THE NEW STANDARD",
    headline: "Designed to be unforgettable.",
    subheadline: "Precision, presence, and performance in one defining product.",
    cta: "Discover now",
  },
  {
    id: "gallery",
    name: "Gallery White",
    category: "Minimal",
    description: "Museum-clean composition for premium consumer products.",
    batch: 1,
    accent: "#111111",
    background: "#f3f0e9",
    surface: "#ffffff",
    foreground: "#111111",
    muted: "#6e6a62",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.88,
    eyebrow: "INTRODUCING",
    headline: "Less noise. More product.",
    subheadline: "A refined object deserves a clear stage.",
    cta: "See the details",
  },
  {
    id: "kinetic",
    name: "Kinetic Grid",
    category: "Technology",
    description: "High-energy modular system for devices and innovation.",
    batch: 1,
    accent: "#7c5cff",
    background: "#0b0c12",
    surface: "#171924",
    foreground: "#ffffff",
    muted: "#a9abc0",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "ENGINEERED FOR MORE",
    headline: "Power, precisely placed.",
    subheadline: "Every detail calibrated for speed and control.",
    cta: "Explore performance",
  },
  {
    id: "aura",
    name: "Aura Bloom",
    category: "Beauty",
    description: "Soft luminous launch for skincare, fragrance, and wellness.",
    batch: 1,
    accent: "#ff7ca8",
    background: "#220f1d",
    surface: "#38182e",
    foreground: "#fff5f8",
    muted: "#dfb8c8",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "MEET YOUR NEW RITUAL",
    headline: "A glow that starts within.",
    subheadline: "An elevated essential made for everyday radiance.",
    cta: "Experience the ritual",
  },
  {
    id: "editorial",
    name: "Editorial Cut",
    category: "Fashion",
    description: "Bold magazine typography with an art-directed product crop.",
    batch: 1,
    accent: "#f04424",
    background: "#e8e1d4",
    surface: "#d4c8b6",
    foreground: "#15130f",
    muted: "#625c53",
    layout: "editorial",
    imageFit: "cover",
    imageScale: 1,
    eyebrow: "THE EDIT",
    headline: "Made to move differently.",
    subheadline: "A new silhouette for the moments that matter.",
    cta: "Shop the edit",
  },
  {
    id: "precision",
    name: "Precision Lab",
    category: "Performance",
    description: "Technical storytelling for engineered and performance goods.",
    batch: 1,
    accent: "#9ef01a",
    background: "#08100c",
    surface: "#111d16",
    foreground: "#ecf7ef",
    muted: "#9bad9f",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.86,
    eyebrow: "BUILT WITHOUT COMPROMISE",
    headline: "Performance you can measure.",
    subheadline: "Advanced materials. Purposeful geometry. Proven results.",
    cta: "View specifications",
  },
  {
    id: "monument",
    name: "Monument",
    category: "Iconic",
    description: "Heroic centered composition that makes one object feel iconic.",
    batch: 1,
    accent: "#ffcf33",
    background: "#15110b",
    surface: "#241d12",
    foreground: "#fff8e8",
    muted: "#c9bfa9",
    layout: "poster",
    imageFit: "contain",
    imageScale: 1,
    eyebrow: "ONE OBJECT. TOTAL PRESENCE.",
    headline: "Meet the icon.",
    subheadline: "Created for those who recognize the exceptional.",
    cta: "Own the moment",
  },
  {
    id: "chromatic",
    name: "Chromatic Pop",
    category: "Social",
    description: "Bold color, oversized type, and playful product movement.",
    batch: 1,
    accent: "#081018",
    background: "#35e0ff",
    surface: "#f8ff46",
    foreground: "#081018",
    muted: "#254551",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.88,
    eyebrow: "JUST DROPPED",
    headline: "Make ordinary impossible.",
    subheadline: "The product built to stand out everywhere.",
    cta: "Get yours",
  },
  {
    id: "launch",
    name: "Launch Signal",
    category: "Campaign",
    description: "Conversion-focused launch narrative with proof-point pacing.",
    batch: 1,
    accent: "#ff5b3d",
    background: "#0e1118",
    surface: "#1a1f2b",
    foreground: "#ffffff",
    muted: "#a9b0c1",
    layout: "split",
    imageFit: "contain",
    imageScale: 0.88,
    eyebrow: "AVAILABLE NOW",
    headline: "The wait is over.",
    subheadline: "A breakthrough product, ready for its first impression.",
    cta: "Launch your order",
  },
  {
    id: "essential",
    name: "Everyday Essential",
    category: "Lifestyle",
    description: "Warm, approachable product storytelling for everyday goods.",
    batch: 1,
    accent: "#1d5d4d",
    background: "#eee6d8",
    surface: "#fbf7ef",
    foreground: "#18352e",
    muted: "#647d75",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.88,
    eyebrow: "BETTER BY DESIGN",
    headline: "Made for every day.",
    subheadline: "Thoughtful details that make the familiar feel exceptional.",
    cta: "Find your essential",
  },
  {
    id: "eclipse",
    name: "Eclipse Luxury",
    category: "Luxury",
    description: "A restrained rim-light reveal for premium objects.",
    batch: 2,
    accent: "#d7b56d",
    background: "#030303",
    surface: "#15120d",
    foreground: "#f7f0df",
    muted: "#a89f8d",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "AN OBJECT OF DISTINCTION",
    headline: "Presence, revealed.",
    subheadline: "Crafted for the moment everything else falls away.",
    cta: "Discover the collection",
  },
  {
    id: "swiss",
    name: "Swiss Specification",
    category: "Precision",
    description: "A rigorous modular product story with measured detail.",
    batch: 2,
    accent: "#ff3b30",
    background: "#f1f0eb",
    surface: "#ffffff",
    foreground: "#111111",
    muted: "#666660",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.88,
    eyebrow: "FORM / FUNCTION / DETAIL",
    headline: "Built with intent.",
    subheadline: "Every line considered. Every detail working harder.",
    cta: "View the system",
  },
  {
    id: "type-impact",
    name: "Type Impact",
    category: "Culture",
    description: "Oversized kinetic typography built around the product.",
    batch: 2,
    accent: "#ffea00",
    background: "#ef2b2d",
    surface: "#101010",
    foreground: "#ffffff",
    muted: "#ffd4cf",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "NO QUIET ENTRANCES",
    headline: "Made to hit different.",
    subheadline: "One product. Maximum signal.",
    cta: "Make it yours",
  },
  {
    id: "triptych",
    name: "Editorial Triptych",
    category: "Editorial",
    description: "Three art-directed crops resolve into one hero image.",
    batch: 2,
    accent: "#bf2b21",
    background: "#ded7c8",
    surface: "#f6f1e7",
    foreground: "#171513",
    muted: "#665e55",
    layout: "editorial",
    imageFit: "cover",
    imageScale: 1,
    eyebrow: "THE OBJECT / THREE VIEWS",
    headline: "Every angle has a point of view.",
    subheadline: "A study in proportion, texture, and character.",
    cta: "See every detail",
  },
  {
    id: "liquid",
    name: "Liquid Bloom",
    category: "Beauty",
    description: "Organic color fields carry a soft floating product reveal.",
    batch: 2,
    accent: "#ff8ab7",
    background: "#fff0f4",
    surface: "#e7c5ff",
    foreground: "#3c1430",
    muted: "#825f78",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "A NEW DAILY RITUAL",
    headline: "Made to feel luminous.",
    subheadline: "A softer approach to everyday transformation.",
    cta: "Begin the ritual",
  },
  {
    id: "blueprint",
    name: "Blueprint Breakdown",
    category: "Engineering",
    description: "Technical callouts map the product before a clean hero finish.",
    batch: 2,
    accent: "#5ee7ff",
    background: "#06192b",
    surface: "#0c2d49",
    foreground: "#e8faff",
    muted: "#8cb8c7",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.86,
    eyebrow: "DESIGNED FROM THE INSIDE OUT",
    headline: "Every detail earns its place.",
    subheadline: "Material, geometry, and performance in one complete system.",
    cta: "Explore the build",
  },
  {
    id: "pop-tile",
    name: "Pop Tile Motion",
    category: "Social",
    description: "A rhythmic color grid turns one product into a visual hook.",
    batch: 2,
    accent: "#ff4d00",
    background: "#ffe600",
    surface: "#5d3bff",
    foreground: "#111111",
    muted: "#4d3d18",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.86,
    eyebrow: "NEW / NOW / EVERYWHERE",
    headline: "Too good to scroll past.",
    subheadline: "Color, character, and instant recognition.",
    cta: "Get it now",
  },
  {
    id: "pedestal",
    name: "Gallery Pedestal",
    category: "Showroom",
    description: "An architectural stage elevates the product into an exhibit.",
    batch: 2,
    accent: "#b69b73",
    background: "#d8d1c5",
    surface: "#eee9e1",
    foreground: "#28241f",
    muted: "#736b61",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "COLLECTION NO. 01",
    headline: "Designed for the room.",
    subheadline: "A singular object with architectural presence.",
    cta: "Enter the gallery",
  },
  {
    id: "countdown",
    name: "Launch Countdown",
    category: "Campaign",
    description: "A signal-driven countdown lands on a decisive product reveal.",
    batch: 2,
    accent: "#ff4b35",
    background: "#080b12",
    surface: "#171c29",
    foreground: "#ffffff",
    muted: "#9ba4b5",
    layout: "split",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "THE DROP IS LIVE",
    headline: "Your wait ends now.",
    subheadline: "The next release has officially arrived.",
    cta: "Secure yours",
  },
  {
    id: "scrapbook",
    name: "Lifestyle Scrapbook",
    category: "Lifestyle",
    description: "Layered paper, labels, and product cutouts create a tactile story.",
    batch: 2,
    accent: "#f06b4f",
    background: "#f3e7cc",
    surface: "#fffaf0",
    foreground: "#24362d",
    muted: "#6c776f",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.88,
    eyebrow: "THE EVERYDAY EDIT",
    headline: "Good design lives with you.",
    subheadline: "Thoughtful, useful, and ready for real life.",
    cta: "Bring it home",
  },
];

export const getProductTemplate = (id: ProductTemplateId) => {
  const template = productTemplates.find((item) => item.id === id);
  if (!template) throw new Error(`Unknown product template: ${id}`);
  return template;
};
