export type ProductTemplateId =
  | "obsidian"
  | "gallery"
  | "kinetic"
  | "aura"
  | "editorial"
  | "precision"
  | "monument"
  | "chromatic"
  | "launch"
  | "essential"
  | "eclipse"
  | "swiss"
  | "type-impact"
  | "triptych"
  | "liquid"
  | "blueprint"
  | "pop-tile"
  | "pedestal"
  | "countdown"
  | "scrapbook"
  | "prism"
  | "material-study"
  | "performance-tunnel"
  | "luxury-catalogue"
  | "color-lab"
  | "unboxing"
  | "feature-orbit"
  | "cinematic-scale"
  | "retail-window"
  | "campaign-finale";

export type ProductTemplate = {
  id: ProductTemplateId;
  name: string;
  category: string;
  description: string;
  batch: 1 | 2 | 3;
  accent: string;
  background: string;
  surface: string;
  foreground: string;
  muted: string;
  layout:
    | "split"
    | "center"
    | "poster"
    | "editorial"
    | "technical";
  imageFit: "contain" | "cover";
  imageScale: number;
  eyebrow: string;
  headline: string;
  subheadline: string;
  cta: string;
};

export const productTemplates: ProductTemplate[] = [
  {
    id: "obsidian",
    name: "Obsidian Reveal",
    category: "Luxury",
    description: "Dark cinematic launch with a focused product reveal.",
    batch: 1,
    accent: "#d8ad55",
    background: "#090909",
    surface: "#141414",
    foreground: "#f7f3ea",
    muted: "#aaa49a",
    layout: "split",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "THE NEW STANDARD",
    headline: "Designed to be unforgettable.",
    subheadline: "Precision, presence, and performance in one defining product.",
    cta: "Discover now",
  },
  {
    id: "gallery",
    name: "Gallery White",
    category: "Minimal",
    description: "Museum-clean composition for premium consumer products.",
    batch: 1,
    accent: "#111111",
    background: "#f3f0e9",
    surface: "#ffffff",
    foreground: "#111111",
    muted: "#6e6a62",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.88,
    eyebrow: "INTRODUCING",
    headline: "Less noise. More product.",
    subheadline: "A refined object deserves a clear stage.",
    cta: "See the details",
  },
  {
    id: "kinetic",
    name: "Kinetic Grid",
    category: "Technology",
    description: "High-energy modular system for devices and innovation.",
    batch: 1,
    accent: "#7c5cff",
    background: "#0b0c12",
    surface: "#171924",
    foreground: "#ffffff",
    muted: "#a9abc0",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "ENGINEERED FOR MORE",
    headline: "Power, precisely placed.",
    subheadline: "Every detail calibrated for speed and control.",
    cta: "Explore performance",
  },
  {
    id: "aura",
    name: "Aura Bloom",
    category: "Beauty",
    description: "Soft luminous launch for skincare, fragrance, and wellness.",
    batch: 1,
    accent: "#ff7ca8",
    background: "#220f1d",
    surface: "#38182e",
    foreground: "#fff5f8",
    muted: "#dfb8c8",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "MEET YOUR NEW RITUAL",
    headline: "A glow that starts within.",
    subheadline: "An elevated essential made for everyday radiance.",
    cta: "Experience the ritual",
  },
  {
    id: "editorial",
    name: "Editorial Cut",
    category: "Fashion",
    description: "Bold magazine typography with an art-directed product crop.",
    batch: 1,
    accent: "#f04424",
    background: "#e8e1d4",
    surface: "#d4c8b6",
    foreground: "#15130f",
    muted: "#625c53",
    layout: "editorial",
    imageFit: "cover",
    imageScale: 1,
    eyebrow: "THE EDIT",
    headline: "Made to move differently.",
    subheadline: "A new silhouette for the moments that matter.",
    cta: "Shop the edit",
  },
  {
    id: "precision",
    name: "Precision Lab",
    category: "Performance",
    description: "Technical storytelling for engineered and performance goods.",
    batch: 1,
    accent: "#9ef01a",
    background: "#08100c",
    surface: "#111d16",
    foreground: "#ecf7ef",
    muted: "#9bad9f",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.86,
    eyebrow: "BUILT WITHOUT COMPROMISE",
    headline: "Performance you can measure.",
    subheadline: "Advanced materials. Purposeful geometry. Proven results.",
    cta: "View specifications",
  },
  {
    id: "monument",
    name: "Monument",
    category: "Iconic",
    description: "Heroic centered composition that makes one object feel iconic.",
    batch: 1,
    accent: "#ffcf33",
    background: "#15110b",
    surface: "#241d12",
    foreground: "#fff8e8",
    muted: "#c9bfa9",
    layout: "poster",
    imageFit: "contain",
    imageScale: 1,
    eyebrow: "ONE OBJECT. TOTAL PRESENCE.",
    headline: "Meet the icon.",
    subheadline: "Created for those who recognize the exceptional.",
    cta: "Own the moment",
  },
  {
    id: "chromatic",
    name: "Chromatic Pop",
    category: "Social",
    description: "Bold color, oversized type, and playful product movement.",
    batch: 1,
    accent: "#081018",
    background: "#35e0ff",
    surface: "#f8ff46",
    foreground: "#081018",
    muted: "#254551",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.88,
    eyebrow: "JUST DROPPED",
    headline: "Make ordinary impossible.",
    subheadline: "The product built to stand out everywhere.",
    cta: "Get yours",
  },
  {
    id: "launch",
    name: "Launch Signal",
    category: "Campaign",
    description: "Conversion-focused launch narrative with proof-point pacing.",
    batch: 1,
    accent: "#ff5b3d",
    background: "#0e1118",
    surface: "#1a1f2b",
    foreground: "#ffffff",
    muted: "#a9b0c1",
    layout: "split",
    imageFit: "contain",
    imageScale: 0.88,
    eyebrow: "AVAILABLE NOW",
    headline: "The wait is over.",
    subheadline: "A breakthrough product, ready for its first impression.",
    cta: "Launch your order",
  },
  {
    id: "essential",
    name: "Everyday Essential",
    category: "Lifestyle",
    description: "Warm, approachable product storytelling for everyday goods.",
    batch: 1,
    accent: "#1d5d4d",
    background: "#eee6d8",
    surface: "#fbf7ef",
    foreground: "#18352e",
    muted: "#647d75",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.88,
    eyebrow: "BETTER BY DESIGN",
    headline: "Made for every day.",
    subheadline: "Thoughtful details that make the familiar feel exceptional.",
    cta: "Find your essential",
  },
  {
    id: "eclipse",
    name: "Eclipse Luxury",
    category: "Luxury",
    description: "A restrained rim-light reveal for premium objects.",
    batch: 2,
    accent: "#d7b56d",
    background: "#030303",
    surface: "#15120d",
    foreground: "#f7f0df",
    muted: "#a89f8d",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "AN OBJECT OF DISTINCTION",
    headline: "Presence, revealed.",
    subheadline: "Crafted for the moment everything else falls away.",
    cta: "Discover the collection",
  },
  {
    id: "swiss",
    name: "Swiss Specification",
    category: "Precision",
    description: "A rigorous modular product story with measured detail.",
    batch: 2,
    accent: "#ff3b30",
    background: "#f1f0eb",
    surface: "#ffffff",
    foreground: "#111111",
    muted: "#666660",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.88,
    eyebrow: "FORM / FUNCTION / DETAIL",
    headline: "Built with intent.",
    subheadline: "Every line considered. Every detail working harder.",
    cta: "View the system",
  },
  {
    id: "type-impact",
    name: "Type Impact",
    category: "Culture",
    description: "Oversized kinetic typography built around the product.",
    batch: 2,
    accent: "#ffea00",
    background: "#ef2b2d",
    surface: "#101010",
    foreground: "#ffffff",
    muted: "#ffd4cf",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "NO QUIET ENTRANCES",
    headline: "Made to hit different.",
    subheadline: "One product. Maximum signal.",
    cta: "Make it yours",
  },
  {
    id: "triptych",
    name: "Editorial Triptych",
    category: "Editorial",
    description: "Three art-directed crops resolve into one hero image.",
    batch: 2,
    accent: "#bf2b21",
    background: "#ded7c8",
    surface: "#f6f1e7",
    foreground: "#171513",
    muted: "#665e55",
    layout: "editorial",
    imageFit: "cover",
    imageScale: 1,
    eyebrow: "THE OBJECT / THREE VIEWS",
    headline: "Every angle has a point of view.",
    subheadline: "A study in proportion, texture, and character.",
    cta: "See every detail",
  },
  {
    id: "liquid",
    name: "Liquid Bloom",
    category: "Beauty",
    description: "Organic color fields carry a soft floating product reveal.",
    batch: 2,
    accent: "#ff8ab7",
    background: "#fff0f4",
    surface: "#e7c5ff",
    foreground: "#3c1430",
    muted: "#825f78",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "A NEW DAILY RITUAL",
    headline: "Made to feel luminous.",
    subheadline: "A softer approach to everyday transformation.",
    cta: "Begin the ritual",
  },
  {
    id: "blueprint",
    name: "Blueprint Breakdown",
    category: "Engineering",
    description: "Technical callouts map the product before a clean hero finish.",
    batch: 2,
    accent: "#5ee7ff",
    background: "#06192b",
    surface: "#0c2d49",
    foreground: "#e8faff",
    muted: "#8cb8c7",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.86,
    eyebrow: "DESIGNED FROM THE INSIDE OUT",
    headline: "Every detail earns its place.",
    subheadline: "Material, geometry, and performance in one complete system.",
    cta: "Explore the build",
  },
  {
    id: "pop-tile",
    name: "Pop Tile Motion",
    category: "Social",
    description: "A rhythmic color grid turns one product into a visual hook.",
    batch: 2,
    accent: "#ff4d00",
    background: "#ffe600",
    surface: "#5d3bff",
    foreground: "#111111",
    muted: "#4d3d18",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.86,
    eyebrow: "NEW / NOW / EVERYWHERE",
    headline: "Too good to scroll past.",
    subheadline: "Color, character, and instant recognition.",
    cta: "Get it now",
  },
  {
    id: "pedestal",
    name: "Gallery Pedestal",
    category: "Showroom",
    description: "An architectural stage elevates the product into an exhibit.",
    batch: 2,
    accent: "#b69b73",
    background: "#d8d1c5",
    surface: "#eee9e1",
    foreground: "#28241f",
    muted: "#736b61",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "COLLECTION NO. 01",
    headline: "Designed for the room.",
    subheadline: "A singular object with architectural presence.",
    cta: "Enter the gallery",
  },
  {
    id: "countdown",
    name: "Launch Countdown",
    category: "Campaign",
    description: "A signal-driven countdown lands on a decisive product reveal.",
    batch: 2,
    accent: "#ff4b35",
    background: "#080b12",
    surface: "#171c29",
    foreground: "#ffffff",
    muted: "#9ba4b5",
    layout: "split",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "THE DROP IS LIVE",
    headline: "Your wait ends now.",
    subheadline: "The next release has officially arrived.",
    cta: "Secure yours",
  },
  {
    id: "scrapbook",
    name: "Lifestyle Scrapbook",
    category: "Lifestyle",
    description: "Layered paper, labels, and product cutouts create a tactile story.",
    batch: 2,
    accent: "#f06b4f",
    background: "#f3e7cc",
    surface: "#fffaf0",
    foreground: "#24362d",
    muted: "#6c776f",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.88,
    eyebrow: "THE EVERYDAY EDIT",
    headline: "Good design lives with you.",
    subheadline: "Thoughtful, useful, and ready for real life.",
    cta: "Bring it home",
  },
  {
    id: "prism",
    name: "Prism Chamber",
    category: "Future Luxury",
    description: "Refracted light planes build a dimensional premium reveal.",
    batch: 3,
    accent: "#8cf5ff",
    background: "#05060c",
    surface: "#17152e",
    foreground: "#f7fbff",
    muted: "#9ca9bd",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "LIGHT / FORM / PRESENCE",
    headline: "See it in a new light.",
    subheadline: "A precise object, revealed through color and dimension.",
    cta: "Enter the prism",
  },
  {
    id: "material-study",
    name: "Material Study",
    category: "Craft",
    description: "Tactile macro panels assemble into a complete product portrait.",
    batch: 3,
    accent: "#c66b3d",
    background: "#ded4c5",
    surface: "#f6f0e7",
    foreground: "#211b17",
    muted: "#74685e",
    layout: "editorial",
    imageFit: "cover",
    imageScale: 1,
    eyebrow: "A STUDY IN MATERIAL",
    headline: "Made to be felt.",
    subheadline: "Texture, finish, and form come together with intention.",
    cta: "Explore the craft",
  },
  {
    id: "performance-tunnel",
    name: "Performance Tunnel",
    category: "Performance",
    description: "Accelerating perspective and telemetry frame a high-speed launch.",
    batch: 3,
    accent: "#c8ff32",
    background: "#030705",
    surface: "#142116",
    foreground: "#f5ffe9",
    muted: "#91a190",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "PERFORMANCE / UNLOCKED",
    headline: "Built for momentum.",
    subheadline: "Every system tuned to move faster, further, and with control.",
    cta: "See the performance",
  },
  {
    id: "luxury-catalogue",
    name: "Luxury Catalogue",
    category: "Fashion",
    description: "A numbered editorial edition with refined page-turn pacing.",
    batch: 3,
    accent: "#811f24",
    background: "#e9e2d6",
    surface: "#faf7f1",
    foreground: "#161310",
    muted: "#6d655c",
    layout: "editorial",
    imageFit: "contain",
    imageScale: 0.92,
    eyebrow: "THE PRIVATE EDITION",
    headline: "An object worth collecting.",
    subheadline: "Considered proportions. Lasting character. Singular presence.",
    cta: "View the edition",
  },
  {
    id: "color-lab",
    name: "Color Laboratory",
    category: "Color",
    description: "Controlled color fields transform around a pristine hero object.",
    batch: 3,
    accent: "#ff4f9a",
    background: "#ffdf3e",
    surface: "#6057ff",
    foreground: "#111019",
    muted: "#493f3c",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "COLOR / COMPOSITION / YOU",
    headline: "Choose your energy.",
    subheadline: "One unmistakable design, expressed in full color.",
    cta: "Find your color",
  },
  {
    id: "unboxing",
    name: "Unboxing Ceremony",
    category: "Reveal",
    description: "Layered packaging doors create anticipation before the hero reveal.",
    batch: 3,
    accent: "#d5b174",
    background: "#15110d",
    surface: "#2a221a",
    foreground: "#fff8eb",
    muted: "#b7aa98",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "THE ARRIVAL",
    headline: "Worth the anticipation.",
    subheadline: "Every layer considered. Every detail waiting to be discovered.",
    cta: "Open the experience",
  },
  {
    id: "feature-orbit",
    name: "Feature Orbit",
    category: "Technology",
    description: "Structured feature satellites revolve around a centered product.",
    batch: 3,
    accent: "#5ee6ff",
    background: "#07101f",
    surface: "#112445",
    foreground: "#f1f8ff",
    muted: "#8ba1bd",
    layout: "technical",
    imageFit: "contain",
    imageScale: 0.86,
    eyebrow: "THE COMPLETE SYSTEM",
    headline: "Everything works together.",
    subheadline: "Core performance surrounded by the features that make it exceptional.",
    cta: "Explore every feature",
  },
  {
    id: "cinematic-scale",
    name: "Cinematic Scale",
    category: "Icon",
    description: "Extreme cinematic crops pull back into a monumental hero frame.",
    batch: 3,
    accent: "#f3c45c",
    background: "#070707",
    surface: "#1a1813",
    foreground: "#fffaf0",
    muted: "#aaa398",
    layout: "poster",
    imageFit: "contain",
    imageScale: 1,
    eyebrow: "BUILT LARGER THAN LIFE",
    headline: "Impossible to overlook.",
    subheadline: "A defining object deserves a cinematic introduction.",
    cta: "Meet the icon",
  },
  {
    id: "retail-window",
    name: "Retail Window",
    category: "Retail",
    description: "A dimensional storefront display turns the product into the destination.",
    batch: 3,
    accent: "#ff735c",
    background: "#d6e7e1",
    surface: "#fff8ee",
    foreground: "#16322f",
    muted: "#627772",
    layout: "center",
    imageFit: "contain",
    imageScale: 0.9,
    eyebrow: "NOW IN THE WINDOW",
    headline: "Stop. Look. Want.",
    subheadline: "A display designed to turn attention into desire.",
    cta: "Shop the window",
  },
  {
    id: "campaign-finale",
    name: "Campaign Finale",
    category: "Campaign",
    description: "A rapid campaign montage resolves into one decisive brand frame.",
    batch: 3,
    accent: "#ff3d26",
    background: "#0b0b0c",
    surface: "#f2eee6",
    foreground: "#ffffff",
    muted: "#b4b1ac",
    layout: "poster",
    imageFit: "contain",
    imageScale: 0.94,
    eyebrow: "THIS IS THE MOMENT",
    headline: "The campaign starts now.",
    subheadline: "One product. One signal. One unforgettable final frame.",
    cta: "Make it yours",
  },
];

export const getProductTemplate = (id: ProductTemplateId) => {
  const template = productTemplates.find((item) => item.id === id);
  if (!template) throw new Error(`Unknown product template: ${id}`);
  return template;
};
